import { AliasTypeSignature, ArkBody, ArkClass, ArkField, ArkFile, ArkMethod, ArkNamespace, BasicBlock, Cfg, ClassSignature, Constant, Decorator, ExportInfo, FieldSignature, FileSignature, ImportInfo, LineColPosition, Local, MethodSignature, NamespaceSignature, Scene, Stmt, Type, Value } from '../..';
import { MethodParameter } from '../../core/model/builder/ArkMethodBuilder';
import { AliasTypeSignatureDto, ArkFileDto, BasicBlockDto, CfgDto, ClassDto, ClassSignatureDto, ConstantDto, DecoratorDto, ExportInfoDto, FieldDto, FieldSignatureDto, FileSignatureDto, ImportInfoDto, LineColPositionDto, LocalDto, MethodBodyDto, MethodDto, MethodParameterDto, MethodSignatureDto, NamespaceDto, NamespaceSignatureDto, SceneDto, StmtDto, TypeDto, ValueDto } from './JsonDto';
export declare function serializeArkScene(scene: Scene): SceneDto;
export declare function serializeArkFile(file: ArkFile): ArkFileDto;
export declare function serializeNamespace(namespace: ArkNamespace): NamespaceDto;
export declare function serializeClass(clazz: ArkClass): ClassDto;
export declare function serializeField(field: ArkField): FieldDto;
export declare function serializeMethod(method: ArkMethod): MethodDto;
export declare function serializeMethodBody(body: ArkBody): MethodBodyDto;
export declare function serializeMethodParameter(parameter: MethodParameter): MethodParameterDto;
export declare function serializeImportInfo(importInfo: ImportInfo): ImportInfoDto;
export declare function serializeExportInfo(exportInfo: ExportInfo): ExportInfoDto;
export declare function serializeDecorator(decorator: Decorator): DecoratorDto;
export declare function serializeLineColPosition(position: LineColPosition): LineColPositionDto;
export declare function serializeType(type: Type): TypeDto;
export declare function serializeFileSignature(file: FileSignature): FileSignatureDto;
export declare function serializeNamespaceSignature(namespace: NamespaceSignature): NamespaceSignatureDto;
export declare function serializeClassSignature(clazz: ClassSignature): ClassSignatureDto;
export declare function serializeFieldSignature(field: FieldSignature): FieldSignatureDto;
export declare function serializeMethodSignature(method: MethodSignature): MethodSignatureDto;
export declare function serializeAliasTypeSignature(signature: AliasTypeSignature): AliasTypeSignatureDto;
export declare function serializeCfg(cfg: Cfg): CfgDto;
export declare function serializeBasicBlock(block: BasicBlock): BasicBlockDto;
export declare function serializeLocal(local: Local): LocalDto;
export declare function serializeConstant(constant: Constant): ConstantDto;
export declare function serializeValue(value: Value): ValueDto;
export declare function serializeStmt(stmt: Stmt): StmtDto;
