export declare const NAME_DELIMITER = "$";
export declare const NAME_PREFIX = "%";
export declare const UNKNOWN_NAME = "unk";
export declare const DEFAULT_NAME = "dflt";
export declare const DEFAULT_ARK_CLASS_NAME: string;
export declare const ANONYMOUS_CLASS_PREFIX: string;
export declare const ANONYMOUS_CLASS_DELIMITER = "$";
export declare const NESTED_CLASS_METHOD_DELIMITER = "-";
export declare const DEFAULT_ARK_METHOD_NAME: string;
export declare const INSTANCE_INIT_METHOD_NAME: string;
export declare const STATIC_INIT_METHOD_NAME: string;
export declare const STATIC_BLOCK_METHOD_NAME_PREFIX: string;
export declare const ANONYMOUS_METHOD_PREFIX: string;
export declare const CALL_SIGNATURE_NAME = "create";
export declare const GETTER_PREFIX = "Get-";
export declare const SETTER_PREFIX = "Set-";
export declare const UNKNOWN_PROJECT_NAME: string;
export declare const UNKNOWN_FILE_NAME: string;
export declare const UNKNOWN_NAMESPACE_NAME: string;
export declare const UNKNOWN_CLASS_NAME = "";
export declare const UNKNOWN_FIELD_NAME = "";
export declare const UNKNOWN_METHOD_NAME = "";
export declare const TEMP_LOCAL_PREFIX = "%";
export declare const LEXICAL_ENV_NAME_PREFIX: string;
export declare const ARKTS_STATIC_MARK = "use static";
export declare const MAKEOBSERVED = "makeObserved";
export declare const CONSTRUCTORFUCNNAME = "constructor";
export declare const POSTMESSAGEFUNCNAME = "postMessage";
export declare const POSTMESSAGEWITHSHAREDSENDABLEFUNCNAME = "postMessageWithSharedSendable";
export declare const ONMESSAGEFUNCNAME = "onmessage";
