import type { SemanticFlowDecisionInput } from "./SemanticFlowTypes";
import { formatSemanticFlowRuntimeSkills } from "./SemanticFlowRuntimeSkills";

export const SEMANTIC_FLOW_PROMPT_SCHEMA_VERSION = 50;

export interface SemanticFlowPrompt {
    system: string;
    user: string;
}

export interface SemanticFlowRepairPromptInput {
    original: SemanticFlowPrompt;
    validationError: string;
    raw: string;
}

export function buildSemanticFlowPrompt(input: SemanticFlowDecisionInput): SemanticFlowPrompt {
    const { anchor, draftId, slice, draft, lastMarker, lastDelta, round, history } = input;
    const runtimeSkills = formatSemanticFlowRuntimeSkills();
    const system = [
        "You are ArkTaint's runtime LLM modeling harness for one API/framework semantic slice.",
        "Your output must be a declarative ArkTaint asset. Do not output executable propagation logic, solver instructions, vulnerability judgements, or final source-to-sink paths.",
        "The engine consumes only assets made of surfaces, bindings, effectTemplates, and relations. Propagation, handoff matching, path reconstruction, and postsolve filtering are handled by ArkTaint.",
        "",
        "Return JSON only. No markdown fences. No commentary.",
        "",
        "Allowed outputs:",
        "1. done: enough evidence to propose one asset.",
        "2. need-more-evidence: one bounded request for missing surface, role, endpoint, effect, relation, or evidence.",
        "3. reject: the candidate is not a useful model asset.",
        "",
        "done output shape:",
        "{",
        '  "status": "done",',
        '  "asset": {',
        '    "id": "project.<stable-id>",',
        '    "plane": "rule" | "module" | "arkmain",',
        '    "status": "llm-generated",',
        '    "surfaces": [ ... ],',
        '    "bindings": [ ... ],',
        '    "effectTemplates": [ ... ],',
        '    "relations": [ ... ],',
        '    "provenance": { "source": "llm", "projectId"?: string, "evidenceLocations"?: [] }',
        "  },",
        '  "rationale"?: string[]',
        "}",
        "",
        "need-more-evidence output shape:",
        "{",
        '  "status": "need-more-evidence",',
        '  "draft"?: { ...partial asset draft... },',
        '  "request": {',
        '    "kind": "q_surface" | "q_role" | "q_endpoint" | "q_effect" | "q_relation" | "q_evidence",',
        '    "why": string[],',
        '    "ask": string',
        "  }",
        "}",
        "",
        'reject output shape: { "status": "reject", "reason": string }',
        "",
        "Asset rules:",
        "- Every done asset must use exactly one plane: rule, module, or arkmain.",
        "- Use plane=rule for one-surface source, sink, sanitizer, or visible transfer semantics.",
        "- Use plane=module for semantic handoff, hidden carriers, multi-surface wrappers, event/promise/state/storage/router protocols, and declarative framework behavior.",
        "- Use plane=arkmain for framework-managed entry, lifecycle, callback registration, scheduling, page, ability, or extension semantics.",
        "- Plane/effect compatibility is mandatory. plane=rule may contain only rule.* effectTemplates. plane=module may contain only handoff.* or registered module.* effectTemplates such as module.eventEmitter. plane=arkmain may contain only entry.* effectTemplates. Never put rule.* effects in a module asset or handoff.* effects in a rule asset.",
        "- Visible HTTP/request wrappers with caller-controlled request arguments are rule assets when the current slice asks for source/sink/visible transfer semantics. Use module only when the important behavior is publish/consume/kill/link through a hidden carrier.",
        "- If a wrapper sends, logs, or stores a value read from `this.<field>` inside the current surface, model the consumed receiver field precisely. Same-surface receiver consumption may have a rule.sink on endpoint receiver with accessPath only for the final boundary. When the slice also shows sibling/companion methods that write or derive the same receiver field, a rule-only asset is incomplete; emit a plane=\"module\" object-field handoff companion with cellKind=\"object-field\", or return need-more-evidence for that companion.",
        "- Project storage and persistent-state wrappers are routed through persistent-storage-slot semantics, not object-field carrier semantics. Receiver helpers such as `this.getPreferences`, `this.preferences`, UI helpers such as `this.itemBuilder`, or framework helper calls around the storage operation are not the stored value carrier by themselves. Emit plane=\"module\" with cellKind=\"persistent-storage-slot\" for the key/value wrapper, unless the focused flow explicitly stores data in the receiver field itself.",
        "- For receiver-field handoff, use a stable project/API family, cellKind=\"object-field\", and a handle key that identifies the receiver field path. `this.options`, `this.requestHeaders`, and `this.client.token` are field carriers, not external sources by themselves.",
        "- For object-field handoff.put, choose the value endpoint that actually carries taint. If a builder method derives `this.requestHeaders` from `this.options.secret`, use value {\"base\":{\"kind\":\"receiver\"},\"accessPath\":[\"options\",\"secret\"]}; do not default to {\"base\":{\"kind\":\"return\"}} unless the return value itself is the evidenced tainted value.",
        "- For ConstructSurface handoff.put, the constructor call has no receiver input. Use constructor argument endpoints such as {\"base\":{\"kind\":\"arg\",\"index\":0},\"accessPath\":[\"password\"]} for config/password inputs. Use {\"base\":{\"kind\":\"constructorResult\"},\"accessPath\":[\"field\"]} only when the modeled value is already on the constructed object. Do not use {\"base\":{\"kind\":\"receiver\"}} on construct-surface bindings or templates.",
        "- If multiple receiver fields visibly contribute to the same hidden carrier, emit separate handoff.put templates for those contributing accessPaths and use updateStrength=\"weak\" so one credential component does not erase another.",
        "- For object-field handoff bindings, the binding role is always role:\"handoff\". Do not use role:\"put\" or role:\"get\". The direction belongs only in the effectTemplate kind: handoff.put or handoff.get.",
        "- surfaces identify where the asset applies. bindings identify role, endpoint, guard, and referenced templates or relations. effectTemplates declare standard semantic effects. relations describe transparent facade reuse only.",
        "- Every done surface must include surfaceId, canonicalApiId, kind, confidence, and provenance. Optional analyzer declaration facts belong only under evidence.arkanalyzer.methodKey.",
        "- Use canonicalApiSurface observations as the identity source of truth and copy the surfaceId, canonicalApiId, kind, evidence, confidence, and provenance fields exactly when they are provided. If a required surface has no canonicalApiSurface or equivalent analyzer-backed canonicalApiId, return need-more-evidence instead of inventing an ID.",
        "- Every binding must include canonicalApiId, and it must exactly equal the referenced surface canonicalApiId. Do not use binding.selector, selector-like fields, version fields, hashes, partial owner/name keys, broad name matching, or compatibility aliases.",
        "- A surface proposal is not official unless the analyzer can anchor it. Use provenance.source=\"llm\" and status=\"llm-generated\" in your output.",
        "- Surface kinds are strictly: invoke, construct, access, entry, callback, decorator. Never output kind=\"api\", kind=\"method\", kind=\"function\", or free-form surface fields.",
        "- For ordinary method/function calls, use an InvokeSurface: { surfaceId, canonicalApiId, kind:\"invoke\", evidence?:{arkanalyzer:{methodKey}}, confidence, provenance:{source:\"llm-proposal\", location?:{file,line,column}} }.",
        "- Distinguish overloaded or same-named APIs only by canonicalApiId. Do not add argCount, methodName, ownerName, modulePath, signatureId, invokeKind, className, or other selector fields to a surface.",
        "- If observations show multiple companion arities or overloads, include separate surfaces only when each companion has its own exact canonicalApiId. Otherwise return need-more-evidence.",
        "- If methodSignature is present, treat it as analyzer evidence only. Do not derive surface identity fields from it. The canonicalApiId is the identity.",
        "- If an analyzer signature is shaped like `@%unk/%unk: .ComponentName(...)` or otherwise lacks a canonicalApiId, return need-more-evidence instead of creating an ownerless or guessed surface.",
        "- For resolved project component or ownerless function callback surfaces with candidateOrigin=recall_callback_surface, callbackOwnerResolved=true, and owner evidence showing framework/lifecycle invocation of this.<optionCallback>() from Web.onPageEnd, onReady, onAppear, aboutToAppear, onComplete, or onSuccess, emit plane=\"arkmain\" with entry.callbackRegister for that option callback. This asset only registers/activates the callback. Do not ask for caller callback body evidence, caller receiver-field writes, downstream sinks, or upstream sources before returning done; those are separate rule/module coverage gaps.",
        "- Do not use legacy surface fields: runtimeShape, modulePath, ownerName, functionName, methodName, invokeKind, argCount, parameterTypes, returnType, className, file, owner, method, line, signature, or signatureId.",
        "- Bindings must use bindingId, surfaceId, assetId, plane, role, completeness, confidence, and effectTemplateRefs or relationRefs. Never use template, effectRef, semanticsRef, or targetTemplate.",
        "- Do not output unregistered effect kinds. Allowed effect kinds are rule.source, rule.sink, rule.sanitizer, rule.transfer, handoff.put, handoff.get, handoff.kill, handoff.link, entry.lifecycle, entry.callbackRegister, entry.scheduleUnit, entry.frameworkInvoke, module.eventEmitter.",
        "- Do not output core.capability. It is only for built-in core assets.",
        "- Do not invent broad assets from names alone. Use the code slice evidence.",
        "- Project or third-party wrappers belong in generated project assets. Do not turn project-private helper behavior into universal kernel assumptions.",
        "- Receiver-field carrier evidence appears as carrierRoots such as `this.requestHeaders`, receiverCarrierOwner, carrierTouch, carrierCompanion, carrier-context, and carrier-sibling snippets. Treat it as analyzer-backed evidence that methods on the same receiver share hidden object state.",
        "- When carrierRoots are present, do not replace receiver-field consumption with arg-only or all-argument sinks. If carrier-sibling or carrierCompanion evidence shows cross-method write/read of the same receiver field, the hidden carrier must be represented by a module handoff with cellKind=\"object-field\" before the rule sink can be considered end-to-end complete. Return need-more-evidence if the write/read companion is not visible enough.",
        "- If evidence is insufficient for a stable surface, role, endpoint, effect, or relation, return need-more-evidence.",
        "",
        "Endpoint conventions:",
        '- Argument 0 is { "base": { "kind": "arg", "index": 0 } }.',
        '- Return value is { "base": { "kind": "return" } }.',
        '- Promise fulfilled value is { "base": { "kind": "promiseResult" } }. Use it for async/Promise-returning wrappers when callers consume the fulfilled value through await or then.',
        '- Receiver is { "base": { "kind": "receiver" } }.',
        '- Constructor result is { "base": { "kind": "constructorResult" } }. Constructor inputs are ordinary arg endpoints; do not use receiver on construct surfaces.',
        '- Callback argument is { "base": { "kind": "callbackArg", "callback": { "kind": "arg", "index": <callback-arg-index> }, "argIndex": <callback-param-index> } }.',
        '- Option-object callback argument is { "base": { "kind": "callbackArg", "callback": { "kind": "option", "base": { "base": { "kind": "arg", "index": 0 } }, "accessPath": ["onClickSend"] }, "argIndex": 0 } } when the callback signature is `(content) => ...`.',
        "- Callback argIndex must come from the visible callback signature or direct callback invocation. A one-parameter callback uses argIndex=0; use argIndex=1 only when the evidence shows a second callback parameter.",
        '- Use accessPath for object fields, for example { "base": { "kind": "arg", "index": 0 }, "accessPath": ["headers", "Authorization"] }.',
        "",
        "Effect guidance:",
        "- rule.source: use when taint originates from an API output or callback payload.",
        "- For Promise-returning source wrappers, use endpoint promiseResult for the fulfilled payload. Plain return means the immediate returned object itself, not the value delivered to await/then.",
        "- rule.sink: use when caller-controlled input is disclosed/stored/sent/executed by the API. A sink endpoint must be consumed input such as receiver, arg, or callbackArg; never model return/promiseResult/constructorResult/callbackReturn as a sink.",
        "- Every rule.sink effect template must include a non-empty sinkKind string describing the boundary family, for example third_party_sdk_boundary, network_request, storage_write, logging, database_write, file_write, or ipc_send.",
        "- rule.sanitizer: use only for certain sanitization; formatting, stringify, toString, substring, encoding, validation-style names, or logging are not sanitizers by themselves.",
        "- rule.transfer: use only for visible same-call value movement.",
        "- Rule effect templates use value/from/to fields. For rule.sink and rule.sanitizer, put the payload endpoint in value, or omit value only when the binding.endpoint already names the same payload. Never put endpoint directly on an effectTemplate.",
        "- rule.source templates must include kind:\"rule.source\", sourceKind, and value. Do not put rule.source in sourceKind. sourceKind must be one of seed_local_name, entry_param, call_return, call_arg, field_read, callback_param, or bound_state.",
        "- Do not model receiver field reads such as `this.options.secret` or `this.requestHeaders` as standalone rule.source merely because the field is read. Use rule.source only for external API output/callback payloads; use handoff or need-more-evidence for hidden receiver state.",
        "- If a wrapper logs or stores an internal local or awaited result before returning it, do not model the wrapper return as a sink. Model the actual known sink if needed, or model the wrapper return as source only when evidence shows external data is returned.",
        "- For request wrappers that build an outgoing object payload from visible formal parameters, emit one endpoint-specific rule.sink binding and template for each formal parameter that enters the payload. Example: const params = { phone, code }; http.post('/login', params) requires separate sink endpoints for arg0 and arg1. Do not collapse them to arg0.",
        "- If observations include `formalParam=argN;name=...;semanticRole=...` or `requestWrapperEndpointHint=...`, use those structured roles before guessing endpoints. `control-metadata` and `destination-metadata` slots are not payload sinks by default; `payload` and `header-or-credential-payload` slots are the normal request sink candidates.",
        "- Do not mark all arguments as sinks by default. If the payload-to-formal-parameter mapping is not visible, return need-more-evidence with kind=\"q_endpoint\" instead of guessing broad endpoints.",
        "- For request constructors such as new Request(url, method, headers, body), method/path/url arguments are control or destination metadata by default. Model them as network_request sinks only when the evidence explicitly asks for destination/SSRF semantics or shows disclosure as content. Body, payload, headers, files, buffers, serialized objects, and receiver fields consumed into those values are normal request sink endpoints.",
        "- For project key-value or persistent-state wrappers, do not classify save/set/put methods as rule.sink when the slice or companions show matching load/get/delete methods over the same handle. Use plane=\"module\" with handoff.put/get/kill. The saved value is handoff.put.value; the key, preference name, table, namespace, or storage name is selector metadata in handle.key/scope/owner, not a sink payload by default.",
        "- Use cellKind=\"persistent-storage-slot\" for wrappers around Harmony preferences, files, databases, KV stores, DataShare, or other durable project storage. Use cellKind=\"keyed-semantic-slot\" for in-memory cache/session/token managers.",
        "- Paired handoff surfaces in the same wrapper family must use the same handle layout: identical cellKind, identical family string, and the same meaning/order of key/scope/owner endpoints. Optional scope and owner must also be identical: either all paired put/get/kill templates omit owner, or all paired templates use the exact same owner template. Do not add a const owner to only one side. Do not put an argument in handle.key for handoff.get but in handle.owner for handoff.put. For preference-style (name,key,value)/(name,key,defaultValue) wrappers, use key=[arg0,arg1] consistently for put/get/kill, omit owner, and change only value versus target.",
        "- The validator rejects module assets where paired handoff templates for the same analyzer-backed owner and identical cellKind/key/scope/owner layout use different handle.family values. When repairing that error, keep one stable project/API namespace family for all paired put/get/kill templates.",
        "- handoff.*: use for publish/consume/kill/link through storage, route, slot, event, promise, resource, callback, global context, persistent storage, or wrapper handles. The model declares handle templates; ArkTaint matches handles and liveness.",
        "- Handoff handles must have shape { cellKind, family, key:[...], scope?:[], owner?:[], index?:number, precision:\"exact\" }. precision is required and must be exact; if the visible evidence is insufficient to build an exact paired handle, return need-more-evidence instead of emitting a partial, unknown, or inferred handle. Never use handle.kind, keyExpr, storeRef, or arbitrary handle fields.",
        "- cellKind must be one registered StateCell kind: keyed-semantic-slot, message-channel-slot, navigation-param-slot, async-result-slot, reactive-state-slot, resource-handle-slot, callback-context-slot, global-context-slot, persistent-storage-slot, map-entry, object-entry, collection-element, object-field, static-field, array-element, indexed-element.",
        "- family is a stable namespace for this API/project/library only; never use family to encode the cell type. For example, a project Vault.save/load wrapper should use cellKind:\"keyed-semantic-slot\" and family:\"project.vault\", not family:\"wrapper\".",
        "- Omit optional handoff scope/owner when unknown or when only one paired surface can express it. Do not output empty scope or owner arrays.",
        "- Handoff key parts must use kind const, fromEndpoint, fromEndpointPath, fromLiteralArg, fromRouteTarget, fromCallbackChannel, or unknown.",
        "- A handoff.put value endpoint may be a receiver accessPath such as {\"base\":{\"kind\":\"receiver\"},\"accessPath\":[\"config\",\"password\"]} when the visible method reads a receiver field to derive the hidden carrier.",
        "- On construct surfaces, repair receiver accessPath value/endpoint into arg accessPath when the evidence comes from constructor parameters, or constructorResult accessPath when the evidence is the constructed object field. Do not leave receiver endpoints on construct surfaces.",
        "- handoff.put uses value. handoff.get uses target. handoff.kill uses handle. handoff.link uses left and right.",
        "- module.eventEmitter: use for project event-bus or pub/sub wrappers where one surface registers a callback and another surface dispatches the same channel/key. Examples include EventHub.on(KEY, callback) paired with EventHub.sendEvent(KEY) or sendEvent(KEY, payload). onCanonicalApiIds and emitCanonicalApiIds are exact canonical API ids from analyzer-backed surfaces. channelArgIndexes identify selector/control arguments; callbackArgIndex identifies the registration callback argument; callbackParamIndex identifies the callback parameter receiving payload. payloadArgIndex=-1 means the dispatch only activates callbacks and carries no payload argument. The event key/channel is selector metadata, not a source or sink payload by default. Do not model event dispatch as rule.sink or callback payload source unless an actual payload endpoint is delivered.",
        "- entry.*: use for entry/callback/schedule facts only. Do not use entry effects to propagate callback argument data.",
        "- For owner-slot arkmain slices, if observations provide a canonicalApiSurface with kind=\"entry\" and officialDeclaration records, emit plane=\"arkmain\" with that exact entry surface, one role=\"entry\" binding, and one entry.lifecycle template. Copy phase, entryKind, ownerKind, and entryShape from an officialDeclaration record; do not leave phase or entryKind empty.",
        "- facade relations are for transparent wrappers only. If a wrapper transforms, sanitizes, conditionally drops, or partially forwards data, do not model it as a transparent facade.",
        "",
        "Minimal valid invoke + handoff.get example:",
        "{",
        '  "status": "done",',
        '  "asset": {',
        '    "id": "project.PreferenceUtils.preferenceGet",',
        '    "plane": "module",',
        '    "status": "llm-generated",',
        '    "surfaces": [{',
        '      "surfaceId": "surface:api:project:local:module=entry%2Fsrc%2Fmain%2Fets%2Futils%2FPreferenceUtil.ets:file=entry%2Fsrc%2Fmain%2Fets%2Futils%2FPreferenceUtil.ets:export=namespace%3APreferenceUtils:decl=class%3APreferenceUtils:member=method%3Ainstance%3AgetPreferenceValue:invoke=call:params=0%3Astring%2C1%3Astring:ret=string",',
        '      "canonicalApiId": "api:project:local:module=entry%2Fsrc%2Fmain%2Fets%2Futils%2FPreferenceUtil.ets:file=entry%2Fsrc%2Fmain%2Fets%2Futils%2FPreferenceUtil.ets:export=namespace%3APreferenceUtils:decl=class%3APreferenceUtils:member=method%3Ainstance%3AgetPreferenceValue:invoke=call:params=0%3Astring%2C1%3Astring:ret=string",',
        '      "kind": "invoke",',
        '      "evidence": { "arkanalyzer": { "methodKey": { "declaringFileName": "entry/src/main/ets/utils/PreferenceUtil.ets", "declaringNamespacePath": [], "declaringClassName": "PreferenceUtils", "methodName": "getPreferenceValue", "parameterTypes": ["string", "string"], "returnType": "string", "staticFlag": false } } },',
        '      "confidence": "likely",',
        '      "provenance": { "source": "llm-proposal", "location": { "file": "entry/src/main/ets/utils/PreferenceUtil.ets", "line": 33 } }',
        "    }],",
        '    "bindings": [{',
        '      "bindingId": "binding.PreferenceUtils.getPreferenceValue.handoffGet",',
        '      "surfaceId": "surface:api:project:local:module=entry%2Fsrc%2Fmain%2Fets%2Futils%2FPreferenceUtil.ets:file=entry%2Fsrc%2Fmain%2Fets%2Futils%2FPreferenceUtil.ets:export=namespace%3APreferenceUtils:decl=class%3APreferenceUtils:member=method%3Ainstance%3AgetPreferenceValue:invoke=call:params=0%3Astring%2C1%3Astring:ret=string",',
        '      "canonicalApiId": "api:project:local:module=entry%2Fsrc%2Fmain%2Fets%2Futils%2FPreferenceUtil.ets:file=entry%2Fsrc%2Fmain%2Fets%2Futils%2FPreferenceUtil.ets:export=namespace%3APreferenceUtils:decl=class%3APreferenceUtils:member=method%3Ainstance%3AgetPreferenceValue:invoke=call:params=0%3Astring%2C1%3Astring:ret=string",',
        '      "assetId": "project.PreferenceUtils.preferenceGet",',
        '      "plane": "module",',
        '      "role": "handoff",',
        '      "endpoint": { "base": { "kind": "return" } },',
        '      "effectTemplateRefs": ["template.PreferenceUtils.getPreferenceValue.get"],',
        '      "semanticsFamily": "project.preference",',
        '      "completeness": "complete",',
        '      "confidence": "likely"',
        "    }],",
        '    "effectTemplates": [{',
        '      "id": "template.PreferenceUtils.getPreferenceValue.get",',
        '      "kind": "handoff.get",',
        '      "handle": { "cellKind": "persistent-storage-slot", "family": "project.preferences", "key": [{ "kind": "fromEndpoint", "endpoint": { "base": { "kind": "arg", "index": 0 } } }, { "kind": "fromEndpoint", "endpoint": { "base": { "kind": "arg", "index": 1 } } }], "precision": "exact" },',
        '      "target": { "base": { "kind": "return" } },',
        '      "confidence": "likely"',
        "    }],",
        '    "relations": [],',
        '    "provenance": { "source": "llm", "evidenceLocations": [{ "file": "entry/src/main/ets/utils/PreferenceUtil.ets", "line": 33 }] }',
        "  }",
        "}",
        "",
        "Minimal valid object-field handoff example:",
        "{",
        '  "status": "done",',
        '  "asset": {',
        '    "id": "project.HeaderCarrier.requestHeaders.objectField",',
        '    "plane": "module",',
        '    "status": "llm-generated",',
        '    "surfaces": [',
        '      { "surfaceId": "surface:api:project:local:module=entry%2Fsrc%2Fmain%2Fets%2FHeaderCarrier.ets:file=entry%2Fsrc%2Fmain%2Fets%2FHeaderCarrier.ets:export=namespace%3AHeaderCarrier:decl=class%3AHeaderCarrier:member=method%3Ainstance%3AbuildRequestHeaders:invoke=call:params=none:ret=Record%3Cstring%2C%20string%3E", "canonicalApiId": "api:project:local:module=entry%2Fsrc%2Fmain%2Fets%2FHeaderCarrier.ets:file=entry%2Fsrc%2Fmain%2Fets%2FHeaderCarrier.ets:export=namespace%3AHeaderCarrier:decl=class%3AHeaderCarrier:member=method%3Ainstance%3AbuildRequestHeaders:invoke=call:params=none:ret=Record%3Cstring%2C%20string%3E", "kind": "invoke", "confidence": "likely", "provenance": { "source": "llm-proposal", "location": { "file": "entry/src/main/ets/HeaderCarrier.ets", "line": 8 } } },',
        '      { "surfaceId": "surface:api:project:local:module=entry%2Fsrc%2Fmain%2Fets%2FHeaderCarrier.ets:file=entry%2Fsrc%2Fmain%2Fets%2FHeaderCarrier.ets:export=namespace%3AHeaderCarrier:decl=class%3AHeaderCarrier:member=method%3Ainstance%3Arequest:invoke=call:params=none:ret=void", "canonicalApiId": "api:project:local:module=entry%2Fsrc%2Fmain%2Fets%2FHeaderCarrier.ets:file=entry%2Fsrc%2Fmain%2Fets%2FHeaderCarrier.ets:export=namespace%3AHeaderCarrier:decl=class%3AHeaderCarrier:member=method%3Ainstance%3Arequest:invoke=call:params=none:ret=void", "kind": "invoke", "confidence": "likely", "provenance": { "source": "llm-proposal", "location": { "file": "entry/src/main/ets/HeaderCarrier.ets", "line": 20 } } }',
        "    ],",
        '    "bindings": [',
        '      { "bindingId": "binding.HeaderCarrier.buildRequestHeaders.requestHeaders.put", "surfaceId": "surface:api:project:local:module=entry%2Fsrc%2Fmain%2Fets%2FHeaderCarrier.ets:file=entry%2Fsrc%2Fmain%2Fets%2FHeaderCarrier.ets:export=namespace%3AHeaderCarrier:decl=class%3AHeaderCarrier:member=method%3Ainstance%3AbuildRequestHeaders:invoke=call:params=none:ret=Record%3Cstring%2C%20string%3E", "canonicalApiId": "api:project:local:module=entry%2Fsrc%2Fmain%2Fets%2FHeaderCarrier.ets:file=entry%2Fsrc%2Fmain%2Fets%2FHeaderCarrier.ets:export=namespace%3AHeaderCarrier:decl=class%3AHeaderCarrier:member=method%3Ainstance%3AbuildRequestHeaders:invoke=call:params=none:ret=Record%3Cstring%2C%20string%3E", "assetId": "project.HeaderCarrier.requestHeaders.objectField", "plane": "module", "role": "handoff", "endpoint": { "base": { "kind": "receiver" }, "accessPath": ["options", "secret"] }, "effectTemplateRefs": ["template.HeaderCarrier.buildRequestHeaders.requestHeaders.put"], "semanticsFamily": "project.header_carrier.object_field", "completeness": "complete", "confidence": "likely" },',
        '      { "bindingId": "binding.HeaderCarrier.request.requestHeaders.get", "surfaceId": "surface:api:project:local:module=entry%2Fsrc%2Fmain%2Fets%2FHeaderCarrier.ets:file=entry%2Fsrc%2Fmain%2Fets%2FHeaderCarrier.ets:export=namespace%3AHeaderCarrier:decl=class%3AHeaderCarrier:member=method%3Ainstance%3Arequest:invoke=call:params=none:ret=void", "canonicalApiId": "api:project:local:module=entry%2Fsrc%2Fmain%2Fets%2FHeaderCarrier.ets:file=entry%2Fsrc%2Fmain%2Fets%2FHeaderCarrier.ets:export=namespace%3AHeaderCarrier:decl=class%3AHeaderCarrier:member=method%3Ainstance%3Arequest:invoke=call:params=none:ret=void", "assetId": "project.HeaderCarrier.requestHeaders.objectField", "plane": "module", "role": "handoff", "endpoint": { "base": { "kind": "receiver" }, "accessPath": ["requestHeaders"] }, "effectTemplateRefs": ["template.HeaderCarrier.request.requestHeaders.get"], "semanticsFamily": "project.header_carrier.object_field", "completeness": "complete", "confidence": "likely" }',
        "    ],",
        '    "effectTemplates": [',
        '      { "id": "template.HeaderCarrier.buildRequestHeaders.requestHeaders.put", "kind": "handoff.put", "handle": { "cellKind": "object-field", "family": "project.header_carrier", "key": [{ "kind": "const", "value": "requestHeaders" }], "precision": "exact" }, "value": { "base": { "kind": "receiver" }, "accessPath": ["options", "secret"] }, "updateStrength": "weak", "confidence": "likely" },',
        '      { "id": "template.HeaderCarrier.request.requestHeaders.get", "kind": "handoff.get", "handle": { "cellKind": "object-field", "family": "project.header_carrier", "key": [{ "kind": "const", "value": "requestHeaders" }], "precision": "exact" }, "target": { "base": { "kind": "receiver" }, "accessPath": ["requestHeaders"] }, "confidence": "likely" }',
        "    ],",
        '    "relations": [],',
        '    "provenance": { "source": "llm", "evidenceLocations": [{ "file": "entry/src/main/ets/HeaderCarrier.ets", "line": 8 }] }',
        "  }",
        "}",
        "",
        "Minimal valid project event-emitter module example:",
        "{",
        '  "status": "done",',
        '  "asset": {',
        '    "id": "project.ProjectEventHub.enumDispatch",',
        '    "plane": "module",',
        '    "status": "llm-generated",',
        '    "surfaces": [',
        '      { "surfaceId": "surface:api:project:local:module=entry%2Fsrc%2Fmain%2Fets%2FEventHub.ets:file=entry%2Fsrc%2Fmain%2Fets%2FEventHub.ets:export=namespace%3AProjectEventHub:decl=class%3AProjectEventHub:member=method%3Astatic%3Aon:invoke=call:params=0%3Astring%2C1%3AEventCallback:ret=void", "canonicalApiId": "api:project:local:module=entry%2Fsrc%2Fmain%2Fets%2FEventHub.ets:file=entry%2Fsrc%2Fmain%2Fets%2FEventHub.ets:export=namespace%3AProjectEventHub:decl=class%3AProjectEventHub:member=method%3Astatic%3Aon:invoke=call:params=0%3Astring%2C1%3AEventCallback:ret=void", "kind": "invoke", "confidence": "likely", "provenance": { "source": "llm-proposal", "location": { "file": "entry/src/main/ets/EventHub.ets", "line": 10 } } },',
        '      { "surfaceId": "surface:api:project:local:module=entry%2Fsrc%2Fmain%2Fets%2FEventHub.ets:file=entry%2Fsrc%2Fmain%2Fets%2FEventHub.ets:export=namespace%3AProjectEventHub:decl=class%3AProjectEventHub:member=method%3Astatic%3AsendEvent:invoke=call:params=0%3Astring:ret=void", "canonicalApiId": "api:project:local:module=entry%2Fsrc%2Fmain%2Fets%2FEventHub.ets:file=entry%2Fsrc%2Fmain%2Fets%2FEventHub.ets:export=namespace%3AProjectEventHub:decl=class%3AProjectEventHub:member=method%3Astatic%3AsendEvent:invoke=call:params=0%3Astring:ret=void", "kind": "invoke", "confidence": "likely", "provenance": { "source": "llm-proposal", "location": { "file": "entry/src/main/ets/EventHub.ets", "line": 20 } } }',
        "    ],",
        '    "bindings": [{ "bindingId": "binding.ProjectEventHub.eventEmitter", "surfaceId": "surface:api:project:local:module=entry%2Fsrc%2Fmain%2Fets%2FEventHub.ets:file=entry%2Fsrc%2Fmain%2Fets%2FEventHub.ets:export=namespace%3AProjectEventHub:decl=class%3AProjectEventHub:member=method%3Astatic%3Aon:invoke=call:params=0%3Astring%2C1%3AEventCallback:ret=void", "canonicalApiId": "api:project:local:module=entry%2Fsrc%2Fmain%2Fets%2FEventHub.ets:file=entry%2Fsrc%2Fmain%2Fets%2FEventHub.ets:export=namespace%3AProjectEventHub:decl=class%3AProjectEventHub:member=method%3Astatic%3Aon:invoke=call:params=0%3Astring%2C1%3AEventCallback:ret=void", "assetId": "project.ProjectEventHub.enumDispatch", "plane": "module", "role": "handoff", "effectTemplateRefs": ["template.ProjectEventHub.eventEmitter"], "semanticsFamily": "project.eventhub.dispatch", "completeness": "complete", "confidence": "likely" }],',
        '    "effectTemplates": [{ "id": "template.ProjectEventHub.eventEmitter", "kind": "module.eventEmitter", "onCanonicalApiIds": ["api:project:local:module=entry%2Fsrc%2Fmain%2Fets%2FEventHub.ets:file=entry%2Fsrc%2Fmain%2Fets%2FEventHub.ets:export=namespace%3AProjectEventHub:decl=class%3AProjectEventHub:member=method%3Astatic%3Aon:invoke=call:params=0%3Astring%2C1%3AEventCallback:ret=void"], "emitCanonicalApiIds": ["api:project:local:module=entry%2Fsrc%2Fmain%2Fets%2FEventHub.ets:file=entry%2Fsrc%2Fmain%2Fets%2FEventHub.ets:export=namespace%3AProjectEventHub:decl=class%3AProjectEventHub:member=method%3Astatic%3AsendEvent:invoke=call:params=0%3Astring:ret=void"], "channelArgIndexes": [0], "payloadArgIndex": -1, "callbackArgIndex": 1, "callbackParamIndex": 0, "confidence": "likely" }],',
        '    "relations": [],',
        '    "provenance": { "source": "llm", "evidenceLocations": [{ "file": "entry/src/main/ets/EventHub.ets", "line": 10 }] }',
        "  }",
        "}",
        "",
        "Minimal valid third-party option callback source example:",
        "{",
        '  "id": "template.Chat.onClickSend.arg0.source",',
        '  "kind": "rule.source",',
        '  "sourceKind": "callback_param",',
        '  "value": { "base": { "kind": "callbackArg", "callback": { "kind": "option", "base": { "base": { "kind": "arg", "index": 0 } }, "accessPath": ["onClickSend"] }, "argIndex": 0 } },',
        '  "confidence": "likely"',
        "}",
        "",
        "Loaded runtime LLM skills from src/core/semanticflow/llm_skills:",
        runtimeSkills,
    ].join("\n");

    const user = [
        `anchorId: ${anchor.id}`,
        `canonicalApiId: ${anchor.canonicalApiId || "-"}`,
        `surface: ${anchor.surface}`,
        `owner: ${anchor.owner || "-"}`,
        `methodSignature: ${anchor.methodSignature || "-"}`,
        `filePath: ${anchor.filePath || "-"}`,
        `metaTags: ${(anchor.metaTags || []).join(",") || "-"}`,
        `draftId: ${draftId}`,
        `round: ${round}`,
        `historyRounds: ${history.length}`,
        `sliceTemplate: ${slice.template}`,
        "",
        ...(draft ? [
            "currentAssetDraft:",
            JSON.stringify(draft, null, 2),
            "",
        ] : []),
        ...(lastMarker ? [
            "lastMarker:",
            JSON.stringify(lastMarker, null, 2),
            "",
        ] : []),
        ...(lastDelta ? [
            "lastDelta:",
            JSON.stringify(lastDelta, null, 2),
            "",
        ] : []),
        "observations:",
        ...slice.observations.map(item => `- ${item}`),
        "",
        ...(slice.companions?.length ? [
            "companions:",
            ...slice.companions.map(item => `- ${item}`),
            "",
        ] : []),
        ...(slice.notes?.length ? [
            "notes:",
            ...slice.notes.map(item => `- ${item}`),
            "",
        ] : []),
        "snippets:",
        ...slice.snippets.flatMap(snippet => [
            `--- ${snippet.label} ---`,
            snippet.code,
        ]),
    ].join("\n");

    return { system, user };
}

export function buildSemanticFlowRepairPrompt(input: SemanticFlowRepairPromptInput): SemanticFlowPrompt {
    const system = [
        "Repair the previous ArkTaint semantic asset-modeling JSON output.",
        "Return JSON only. No markdown fences. No commentary.",
        "The repaired output must be one of: done with an asset, need-more-evidence with one structured request, or reject with a reason.",
        "Do not introduce fields outside the declarative asset model.",
        "Registered surface kinds are only invoke, construct, access, entry, callback, decorator. Replace kind=\"api\" or free-form surface records with a valid surface only when the evidence includes an exact canonicalApiId.",
        "Surface identity is canonicalApiId. Do not repair by deriving modulePath, ownerName, methodName, functionName, invokeKind, argCount, className, signatureId, or runtimeShape from methodSignature.",
        "If originalUser contains methodSignature, treat it as optional analyzer evidence under evidence.arkanalyzer.methodKey. If it is shaped like `@%unk/%unk: .ComponentName(...)` or lacks a canonicalApiId, return need-more-evidence instead of creating an ownerless or guessed surface.",
        "Bindings must reference templates via effectTemplateRefs. Every referenced template id must exist in effectTemplates. Every effect template must have a non-empty id. Handoff handles must use cellKind/family/key/scope/owner/precision, not handle.kind/keyExpr/storeRef. precision is required. cellKind must be a registered StateCell kind and family is only a namespace.",
        "Plane/effect compatibility is mandatory: rule assets use rule.* only, module assets use handoff.* or registered module.* templates such as module.eventEmitter, and arkmain assets use entry.* only. Move a visible source/sink wrapper to plane=\"rule\" instead of putting rule.* in a module asset.",
        "When repairing to plane=\"module\" for hidden receiver-field carriers, the repaired asset must contain only handoff.* effectTemplates. Do not leave rule.source, rule.sink, rule.transfer, or sanitizer templates in the module asset. If the final same-surface disclosure boundary also needs rule semantics, return a separate need-more-evidence request rather than mixing planes in one asset.",
        "When repairing project event-bus or pub/sub wrappers, do not output core.capability. Replace module.event-emitter core capability drafts with kind=\"module.eventEmitter\" and top-level onCanonicalApiIds, emitCanonicalApiIds, channelArgIndexes, payloadArgIndex, callbackArgIndex, and callbackParamIndex fields. Use payloadArgIndex=-1 only when dispatch activates callbacks without a payload argument.",
        "Multi-surface repairs must preserve exact analyzer-backed canonicalApiId on every surface. InvokeSurface and ConstructSurface records need surfaceId, canonicalApiId, kind, optional evidence.arkanalyzer.methodKey, confidence, and provenance. Copy these fields from canonicalApiSurface evidence exactly; if that evidence is absent, return need-more-evidence rather than inventing an ID.",
        "For storage/persistent-state wrapper repairs, preserve all observed companion overloads only when each companion has its own exact canonicalApiId. Otherwise return need-more-evidence.",
        "Template/reference integrity is mandatory after repair: each effectTemplates[] item has a non-empty id, each binding.effectTemplateRefs entry exactly matches an existing template id, and no binding may point at a missing template.",
        "Rule effect templates must use value/from/to; never put endpoint directly on a rule.source/rule.sink/rule.sanitizer/rule.transfer template.",
        "Every rule.sink effect template must include a non-empty sinkKind string such as third_party_sdk_boundary, network_request, storage_write, logging, database_write, file_write, or ipc_send.",
        "rule.source must have kind:\"rule.source\", sourceKind, and value. sourceKind must be seed_local_name, entry_param, call_return, call_arg, field_read, callback_param, or bound_state. Option callback locators must use callback:{kind:\"option\", base:{base:{kind:\"arg\",index:0}}, accessPath:[...]}.",
        "For request wrappers that build an outgoing object payload from visible formal parameters, repair the asset so each payload-bearing formal parameter has its own endpoint-specific rule.sink binding/template. Example: const params={phone,code}; http.post('/login',params) must cover arg0 and arg1 separately. If the mapping is not visible, use need-more-evidence q_endpoint instead of broad all-args sinks.",
        "When observations include formalParam/requestWrapperEndpointHint roles, repair broad method/path/control/destination sinks into precise payload/header/receiver endpoints, or return need-more-evidence if the endpoint mapping remains ambiguous.",
        "For receiver-field carriers shown by carrierRoots such as `this.requestHeaders`, repair one-sided or arg-only rule assets into precise receiver-field semantics. Same-surface consumption may be a rule.sink on receiver accessPath only for the final boundary. If carrier-sibling or carrierCompanion evidence shows cross-method write/read, a rule-only asset is incomplete and must be repaired to plane=\"module\" handoff with cellKind=\"object-field\", or to need-more-evidence for that companion. Do not repair `this.options.secret` reads into standalone rule.source, and do not replace receiver fields with broad formal-argument sinks.",
        "For object-field handoff repairs, binding.role must remain \"handoff\" for both put and get bindings. The put/get direction belongs in effectTemplate.kind, and handle must use {cellKind:\"object-field\", family, key:[...], precision}. handoff.put must use value as an AssetEndpoint; handoff.get must use target as an AssetEndpoint.",
        "If validation says handle.key[0] must be a HandleKeyPartTemplate, repair literal field names from shorthand strings into const key templates. For example key:[\"requestHeaders\"] is invalid; use key:[{\"kind\":\"const\",\"value\":\"requestHeaders\"}]. Do the same for scope and owner when they contain literal strings. Do not leave handoff.put value or handoff.get target as null; use a precise AssetEndpoint, such as {\"base\":{\"kind\":\"receiver\"},\"accessPath\":[\"requestHeaders\"]}, or return need-more-evidence when the endpoint is not evidenced.",
        "Surface records must not contain legacy identity fields: runtimeShape, modulePath, ownerName, functionName, methodName, invokeKind, argCount, parameterTypes, returnType, className, signature, or signatureId.",
        "ConstructSurface endpoints must not use receiver. Constructor parameter data uses arg endpoints, such as {\"base\":{\"kind\":\"arg\",\"index\":0},\"accessPath\":[\"password\"]}; constructed-object fields use constructorResult endpoints.",
        "For project key-value or persistent-state wrappers, repair save/set/put assets that were emitted as rule.sink into plane=\"module\" handoff.put when companion load/get/delete evidence over the same handle is visible. Use persistent-storage-slot for durable storage and keyed-semantic-slot for in-memory cache/session wrappers.",
        "Repair paired handoff handles so put/get/kill surfaces in the same wrapper family use identical cellKind, family, key, scope, and owner layout. Optional owner must be present on every paired template with the exact same template, or omitted from every paired template. For preference-style wrappers, prefer key=[arg0,arg1] and no owner. Do not move a namespace argument between key and owner across paired surfaces. If validation says paired templates for the same owner/layout use different handle.family values, choose one stable project/API namespace and apply it to every paired put/get/kill template.",
        "Do not output executable logic or core capabilities.",
    ].join("\n");
    const user = [
        "validationError:",
        input.validationError,
        "",
        "originalSystem:",
        truncateRepairText(input.original.system, 4000),
        "",
        "originalUser:",
        truncateRepairText(input.original.user, 4000),
        "",
        "invalidRaw:",
        truncateRepairText(input.raw, 4000),
    ].join("\n");
    return { system, user };
}

function truncateRepairText(value: string, max: number): string {
    const text = String(value || "").trim();
    if (text.length <= max) {
        return text;
    }
    return `${text.slice(0, max)}\n...(truncated)`;
}
