import type { ArkMainSpec } from "../entry/arkmain/ArkMainSpec";
import type {
    ModuleConstraint,
    ModuleDispatch,
    ModuleEndpoint,
    ModuleSpec,
} from "../kernel/contracts/ModuleSpec";
import { canonicalizeModuleSpec } from "../orchestration/modules/ModuleSpecCanonicalizer";
import { validateModuleSpecOrThrow } from "../orchestration/modules/ModuleSpecValidator";
import type {
    RuleEndpoint,
    RuleEndpointOrRef,
    SinkRule,
    SanitizerRule,
    SourceRule,
    TaintRuleSet,
    TransferRule,
} from "../rules/RuleSchema";
import type {
    SemanticFlowAnalysisAugment,
    SemanticFlowAnchor,
    SemanticFlowArkMainArtifact,
    SemanticFlowArtifact,
    SemanticFlowArtifactClass,
    SemanticFlowEngineAugment,
    SemanticFlowItemResult,
    SemanticFlowModuleArtifact,
    SemanticFlowRuleArtifact,
    SemanticFlowSummary,
    SemanticFlowSurfaceSlotRef,
} from "./SemanticFlowTypes";

export function classifySemanticFlowSummary(
    _anchor: SemanticFlowAnchor,
    summary: SemanticFlowSummary,
    hint?: SemanticFlowArtifactClass,
): SemanticFlowArtifactClass | undefined {
    if (!hint) {
        return undefined;
    }
    if (hint === "arkmain" && isEntryLike(summary)) {
        return "arkmain";
    }
    if (hint === "rule" && isRuleLike(summary)) {
        return "rule";
    }
    if (hint === "module" && isModuleLike(summary)) {
        return "module";
    }
    return undefined;
}

export function buildSemanticFlowArtifact(
    anchor: SemanticFlowAnchor,
    summary: SemanticFlowSummary,
    classification: SemanticFlowArtifactClass,
): SemanticFlowArtifact {
    if (classification === "arkmain") {
        return buildArkMainArtifact(anchor, summary);
    }
    if (classification === "module") {
        return buildModuleArtifact(anchor, summary);
    }
    return buildRuleArtifact(anchor, summary);
}

export function buildSemanticFlowAnalysisAugment(items: SemanticFlowItemResult[]): SemanticFlowAnalysisAugment {
    const ruleSet: TaintRuleSet = {
        schemaVersion: "2.0",
        meta: {
            name: "semanticflow-artifacts",
            description: "Generated by unified semantic flow pipeline.",
            updatedAt: new Date().toISOString().slice(0, 10),
        },
        sources: [],
        sinks: [],
        sanitizers: [],
        transfers: [],
    };
    const moduleSpecs: ModuleSpec[] = [];
    const arkMainSpecs: ArkMainSpec[] = [];

    for (const item of items) {
        if (!item.artifact) {
            continue;
        }
        if (item.artifact.kind === "rule") {
            ruleSet.sources.push(...(item.artifact.ruleSet.sources || []));
            ruleSet.sinks.push(...(item.artifact.ruleSet.sinks || []));
            ruleSet.sanitizers!.push(...(item.artifact.ruleSet.sanitizers || []));
            ruleSet.transfers.push(...(item.artifact.ruleSet.transfers || []));
            continue;
        }
        if (item.artifact.kind === "module") {
            moduleSpecs.push(item.artifact.moduleSpec);
            continue;
        }
        arkMainSpecs.push(item.artifact.spec);
    }

    return {
        ruleSet: dedupeRuleSet(ruleSet),
        moduleSpecs: dedupeModuleSpecs(moduleSpecs),
        arkMainSpecs: dedupeArkMainSpecs(arkMainSpecs),
    };
}

export function mergeSemanticFlowAnalysisAugments(
    augments: SemanticFlowAnalysisAugment[],
): SemanticFlowAnalysisAugment {
    const ruleSet: TaintRuleSet = {
        schemaVersion: "2.0",
        meta: {
            name: "semanticflow-artifacts",
            description: "Merged semantic flow artifacts.",
            updatedAt: new Date().toISOString().slice(0, 10),
        },
        sources: [],
        sinks: [],
        sanitizers: [],
        transfers: [],
    };
    const moduleSpecs: ModuleSpec[] = [];
    const arkMainSpecs: ArkMainSpec[] = [];

    for (const augment of augments) {
        ruleSet.sources.push(...(augment.ruleSet.sources || []));
        ruleSet.sinks.push(...(augment.ruleSet.sinks || []));
        ruleSet.sanitizers!.push(...(augment.ruleSet.sanitizers || []));
        ruleSet.transfers.push(...(augment.ruleSet.transfers || []));
        moduleSpecs.push(...(augment.moduleSpecs || []));
        arkMainSpecs.push(...(augment.arkMainSpecs || []));
    }

    return {
        ruleSet: dedupeRuleSet(ruleSet),
        moduleSpecs: dedupeModuleSpecs(moduleSpecs),
        arkMainSpecs: dedupeArkMainSpecs(arkMainSpecs),
    };
}

export function buildSemanticFlowEngineAugment(augment: SemanticFlowAnalysisAugment): SemanticFlowEngineAugment {
    return {
        sourceRules: augment.ruleSet.sources || [],
        sinkRules: augment.ruleSet.sinks || [],
        sanitizerRules: augment.ruleSet.sanitizers || [],
        transferRules: augment.ruleSet.transfers || [],
        moduleSpecs: augment.moduleSpecs,
        arkMainSpecs: augment.arkMainSpecs,
    };
}

function isEntryLike(summary: SemanticFlowSummary): boolean {
    return Boolean(summary.relations?.entryPattern);
}

function isModuleLike(summary: SemanticFlowSummary): boolean {
    if (summary.moduleSpec || summary.moduleKind) {
        return true;
    }
    return Boolean(
        (summary.relations?.companions && summary.relations.companions.length > 0)
        || summary.relations?.carrier
        || summary.relations?.trigger
        || (summary.relations?.constraints && summary.relations.constraints.length > 0),
    );
}

function isRuleLike(summary: SemanticFlowSummary): boolean {
    if (summary.ruleKind) {
        return true;
    }
    return summary.transfers.length > 0 || summary.inputs.length > 0 || summary.outputs.length > 0;
}

function buildArkMainArtifact(anchor: SemanticFlowAnchor, summary: SemanticFlowSummary): SemanticFlowArkMainArtifact {
    if (!anchor.arkMainSelector) {
        throw new Error(`arkmain artifact requires anchor.arkMainSelector: ${anchor.id}`);
    }
    const entry = summary.relations?.entryPattern;
    if (!entry) {
        throw new Error(`arkmain summary requires relations.entryPattern: ${anchor.id}`);
    }
    return {
        kind: "arkmain",
        spec: {
            enabled: true,
            description: `Generated by semantic flow pipeline for ${anchor.surface}.`,
            selector: anchor.arkMainSelector,
            entryPattern: {
                phase: entry.phase,
                kind: entry.kind,
                ownerKind: entry.ownerKind,
                schedule: entry.schedule ?? true,
                reason: entry.reason || `semanticflow:${anchor.surface}`,
                entryFamily: entry.entryFamily,
                entryShape: entry.entryShape,
            },
        },
    };
}

function buildRuleArtifact(anchor: SemanticFlowAnchor, summary: SemanticFlowSummary): SemanticFlowRuleArtifact {
    const signature = requireAnchorSignature(anchor);
    const idBase = sanitizeId(`semanticflow.${anchor.id}`);
    const ruleKind = inferRuleKind(summary);

    const ruleSet: TaintRuleSet = {
        schemaVersion: "2.0",
        meta: {
            name: `${idBase}.rules`,
            description: `Generated from semantic flow pipeline for ${anchor.surface}.`,
            updatedAt: new Date().toISOString().slice(0, 10),
        },
        sources: [],
        sinks: [],
        sanitizers: [],
        transfers: [],
    };

    if (ruleKind === "source") {
        const targets = summary.outputs;
        if (targets.length === 0) {
            throw new Error(`source rule summary requires at least one output slot: ${anchor.id}`);
        }
        ruleSet.sources.push(...targets.map((target, index) =>
            buildSourceRule(signature, sourceRuleId(idBase, index), summary, target),
        ));
        return { kind: "rule", ruleSet };
    }

    if (ruleKind === "sink") {
        const targets = summary.inputs.length > 0 ? summary.inputs : summary.outputs;
        if (targets.length === 0) {
            throw new Error(`sink rule summary requires at least one input/output slot: ${anchor.id}`);
        }
        ruleSet.sinks.push(...targets.map((target, index) => ({
            id: sinkRuleId(idBase, index),
            enabled: true,
            description: `Generated sink rule for ${anchor.surface}.`,
            tags: ["semanticflow", "llm"],
            match: {
                kind: "signature_equals",
                value: signature,
            },
            target: toRuleEndpoint(target),
        } satisfies SinkRule)));
        return { kind: "rule", ruleSet };
    }

    if (ruleKind === "sanitizer") {
        const targets = summary.inputs.length > 0 ? summary.inputs : summary.outputs;
        if (targets.length === 0) {
            throw new Error(`sanitizer rule summary requires at least one input/output slot: ${anchor.id}`);
        }
        ruleSet.sanitizers!.push(...targets.map((target, index) => ({
            id: sanitizerRuleId(idBase, index),
            enabled: true,
            description: `Generated sanitizer rule for ${anchor.surface}.`,
            tags: ["semanticflow", "llm"],
            match: {
                kind: "signature_equals",
                value: signature,
            },
            target: toRuleEndpoint(target),
        } satisfies SanitizerRule)));
        return { kind: "rule", ruleSet };
    }

    if (summary.transfers.length === 0) {
        throw new Error(`transfer rule summary requires at least one transfer: ${anchor.id}`);
    }
    ruleSet.transfers.push(...summary.transfers.map((transfer, index) => ({
        id: transferRuleId(idBase, index),
        enabled: true,
        description: `Generated transfer rule for ${anchor.surface}.`,
        tags: ["semanticflow", "llm"],
        match: {
            kind: "signature_equals",
            value: signature,
        },
        from: toRuleEndpoint(transfer.from),
        to: toRuleEndpoint(transfer.to),
    } satisfies TransferRule)));
    return { kind: "rule", ruleSet };
}

function buildSourceRule(
    signature: string,
    ruleId: string,
    summary: SemanticFlowSummary,
    target: SemanticFlowSurfaceSlotRef,
): SourceRule {
    const sourceKind = summary.sourceKind || inferSourceKind(target);
    const callbackArgIndexes = target.slot === "callback_param"
        ? [target.callbackArgIndex ?? 0]
        : undefined;
    return {
        id: ruleId,
        enabled: true,
        description: `Generated source rule for ${signature}.`,
        tags: ["semanticflow", "llm"],
        match: {
            kind: "signature_equals",
            value: signature,
        },
        sourceKind,
        target: toSourceRuleTarget(target),
        callbackArgIndexes,
    };
}

function inferSourceKind(target: SemanticFlowSurfaceSlotRef) {
    if (target.slot === "callback_param") return "callback_param" as const;
    if (target.slot === "result") return "call_return" as const;
    if (target.slot === "field_load") return "field_read" as const;
    if (target.slot === "arg") return "entry_param" as const;
    throw new Error(`cannot infer sourceKind from slot ${target.slot}`);
}

function toSourceRuleTarget(target: SemanticFlowSurfaceSlotRef): RuleEndpointOrRef {
    if (target.slot === "callback_param") {
        return { endpoint: `arg${target.paramIndex ?? 0}` as RuleEndpoint };
    }
    return toRuleEndpoint(target);
}

function inferRuleKind(summary: SemanticFlowSummary): "source" | "sink" | "sanitizer" | "transfer" {
    if (summary.ruleKind) {
        return summary.ruleKind;
    }
    if (summary.transfers.length > 0) return "transfer";
    if (summary.inputs.length === 0 && summary.outputs.length > 0) return "source";
    if (summary.inputs.length > 0 && summary.outputs.length === 0) return "sink";
    return "transfer";
}

function buildModuleArtifact(anchor: SemanticFlowAnchor, summary: SemanticFlowSummary): SemanticFlowModuleArtifact {
    const moduleSpec = summary.moduleSpec
        ? canonicalizeAndValidate(materializeSemanticFlowModuleSpec(anchor, summary.moduleSpec))
        : inferModuleSpec(anchor, summary);
    return {
        kind: "module",
        moduleSpec,
    };
}

function materializeSemanticFlowModuleSpec(anchor: SemanticFlowAnchor, spec: ModuleSpec): ModuleSpec {
    const moduleId = sanitizeId(`semanticflow.${anchor.id}`);
    const ownerClassName = extractAnchorOwnerClassName(anchor);
    return {
        ...spec,
        id: !spec.id || spec.id === "__semanticflow_inline__" ? moduleId : spec.id,
        description: spec.description || `Generated by semantic flow pipeline for ${anchor.surface}.`,
        enabled: spec.enabled ?? true,
        semantics: spec.semantics.map(semantic => {
            if (semantic.kind !== "keyed_storage") {
                return semantic;
            }
            const storageClasses = semantic.storageClasses.map(item =>
                item === "__anchor_owner__" && ownerClassName ? ownerClassName : item,
            );
            return {
                ...semantic,
                storageClasses,
            };
        }),
    };
}

function inferModuleSpec(anchor: SemanticFlowAnchor, summary: SemanticFlowSummary): ModuleSpec {
    if (summary.moduleKind === "state" || summary.moduleKind === "declarative") {
        throw new Error(`moduleKind ${summary.moduleKind} requires explicit moduleSpec for ${anchor.id}`);
    }
    if (summary.transfers.length === 0) {
        throw new Error(`module summary requires at least one transfer or explicit moduleSpec: ${anchor.id}`);
    }
    const semantics = summary.transfers.map((transfer, index) => ({
        id: index === 0 ? undefined : `bridge-${index}`,
        kind: "bridge" as const,
        from: toModuleEndpoint(anchor, transfer.from),
        to: toModuleEndpoint(anchor, transfer.to),
        constraints: normalizeModuleConstraints(summary.relations?.constraints),
        dispatch: summary.relations?.trigger ? toModuleDispatch(anchor, summary) : undefined,
    }));
    return canonicalizeAndValidate({
        id: sanitizeId(`semanticflow.${anchor.id}`),
        description: `Generated by semantic flow pipeline for ${anchor.surface}.`,
        enabled: true,
        semantics,
    });
}

function normalizeModuleConstraints(constraints?: ModuleConstraint[]): ModuleConstraint[] | undefined {
    if (!constraints || constraints.length === 0) {
        return undefined;
    }
    const hasSameAddress = constraints.some(constraint => constraint.kind === "same_address");
    const normalized = hasSameAddress
        ? constraints.filter(constraint => constraint.kind !== "same_receiver")
        : constraints;
    return normalized.length > 0 ? normalized : undefined;
}

function canonicalizeAndValidate(spec: ModuleSpec): ModuleSpec {
    validateModuleSpecOrThrow(spec);
    return canonicalizeModuleSpec(spec);
}

function toModuleDispatch(anchor: SemanticFlowAnchor, summary: SemanticFlowSummary): ModuleDispatch {
    const trigger = summary.relations?.trigger;
    if (!trigger) {
        throw new Error(`missing trigger for ${anchor.id}`);
    }
    return {
        preset: trigger.preset,
        via: trigger.via ? toModuleEndpoint(anchor, trigger.via) : undefined,
        reason: trigger.reason,
    };
}

function toModuleEndpoint(anchor: SemanticFlowAnchor, ref: SemanticFlowSurfaceSlotRef): ModuleEndpoint {
    const base = {
        surface: ref.surface || anchor.surface,
        ...(ref.fieldPath ? { fieldPath: ref.fieldPath } : {}),
    };
    switch (ref.slot) {
        case "arg":
            if (typeof ref.index !== "number") throw new Error(`arg slot requires index for ${anchor.id}`);
            return { ...base, slot: "arg", index: ref.index };
        case "base":
            return { ...base, slot: "base" };
        case "result":
            return { ...base, slot: "result" };
        case "callback_param":
            return {
                ...base,
                slot: "callback_param",
                callbackArgIndex: ref.callbackArgIndex,
                paramIndex: ref.paramIndex,
            };
        case "method_this":
            return { ...base, slot: "method_this" };
        case "method_param":
            if (typeof ref.paramIndex !== "number") throw new Error(`method_param slot requires paramIndex for ${anchor.id}`);
            return { ...base, slot: "method_param", paramIndex: ref.paramIndex };
        case "field_load":
            if (!ref.fieldName) throw new Error(`field_load slot requires fieldName for ${anchor.id}`);
            return { ...base, slot: "field_load", fieldName: ref.fieldName };
        case "decorated_field_value":
            return { ...base, slot: "decorated_field_value" };
        default:
            throw new Error(`unsupported module endpoint slot ${(ref as any).slot}`);
    }
}

function toRuleEndpoint(ref: SemanticFlowSurfaceSlotRef): RuleEndpointOrRef {
    const path = normalizeFieldPath(ref.fieldPath);
    if (ref.slot === "arg") {
        if (typeof ref.index !== "number") throw new Error("arg slot requires index");
        return path ? { endpoint: `arg${ref.index}` as RuleEndpoint, path } : (`arg${ref.index}` as RuleEndpoint);
    }
    if (ref.slot === "result") return path ? { endpoint: "result", path } : "result";
    if (ref.slot === "base") return path ? { endpoint: "base", path } : "base";
    if (ref.slot === "field_load") {
        return {
            endpoint: "base",
            path: [ref.fieldName || ""].filter(Boolean),
        };
    }
    throw new Error(`slot ${ref.slot} is not representable as a rule endpoint`);
}

function normalizeFieldPath(fieldPath?: any): string[] | undefined {
    if (!fieldPath) return undefined;
    return Array.isArray(fieldPath) ? fieldPath.map(part => String(part)) : undefined;
}

function requireAnchorSignature(anchor: SemanticFlowAnchor): string {
    const signature = anchor.methodSignature || anchor.method?.getSignature?.()?.toString?.();
    if (!signature) {
        throw new Error(`anchor.methodSignature missing: ${anchor.id}`);
    }
    return signature;
}

function extractAnchorOwnerClassName(anchor: SemanticFlowAnchor): string | undefined {
    const owner = String(anchor.owner || "").trim();
    if (!owner) {
        return undefined;
    }
    const colonIndex = owner.lastIndexOf(":");
    const raw = colonIndex >= 0 ? owner.slice(colonIndex + 1) : owner;
    const normalized = raw.trim();
    return normalized || undefined;
}

function dedupeModuleSpecs(specs: ModuleSpec[]): ModuleSpec[] {
    const out = new Map<string, ModuleSpec>();
    for (const spec of specs) {
        const canonical = canonicalizeAndValidate(spec);
        const key = JSON.stringify(canonical);
        if (!out.has(key)) {
            out.set(key, canonical);
        }
    }
    return [...out.values()];
}

function dedupeArkMainSpecs(specs: ArkMainSpec[]): ArkMainSpec[] {
    const out = new Map<string, ArkMainSpec>();
    for (const spec of specs) {
        const key = JSON.stringify(spec);
        if (!out.has(key)) {
            out.set(key, spec);
        }
    }
    return [...out.values()];
}

function dedupeRuleSet(ruleSet: TaintRuleSet): TaintRuleSet {
    return {
        ...ruleSet,
        sources: dedupeRulesById(ruleSet.sources || []),
        sinks: dedupeRulesById(ruleSet.sinks || []),
        sanitizers: dedupeRulesById(ruleSet.sanitizers || []),
        transfers: dedupeRulesById(ruleSet.transfers || []),
    };
}

function dedupeRulesById<T extends { id?: string }>(rules: T[]): T[] {
    const out = new Map<string, T>();
    const passthrough: T[] = [];
    for (const rule of rules) {
        const key = typeof rule.id === "string" && rule.id.trim().length > 0
            ? rule.id.trim()
            : undefined;
        if (!key) {
            passthrough.push(rule);
            continue;
        }
        if (!out.has(key)) {
            out.set(key, rule);
        }
    }
    return [...out.values(), ...passthrough];
}

function sanitizeId(value: string): string {
    const normalized = value
        .toLowerCase()
        .replace(/[^a-z0-9.-]+/g, "-")
        .replace(/-+/g, "-")
        .replace(/\.+/g, ".")
        .replace(/^[-.]+|[-.]+$/g, "");
    return normalized || "semanticflow";
}

function sourceRuleId(idBase: string, index: number): string {
    return index === 0 ? `${idBase}.source` : `${idBase}.source.${index}`;
}

function sinkRuleId(idBase: string, index: number): string {
    return index === 0 ? `${idBase}.sink` : `${idBase}.sink.${index}`;
}

function sanitizerRuleId(idBase: string, index: number): string {
    return index === 0 ? `${idBase}.sanitizer` : `${idBase}.sanitizer.${index}`;
}

function transferRuleId(idBase: string, index: number): string {
    return index === 0 ? `${idBase}.transfer` : `${idBase}.transfer.${index}`;
}

