import type { SemanticFlowDecisionInput } from "./SemanticFlowTypes";
import {
    collectSemanticFlowSlotAliases,
    formatSemanticFlowSlotAlias,
} from "./SemanticFlowSlotAliases";
import { formatSemanticFlowRuntimeSkills } from "./SemanticFlowRuntimeSkills";

/** Bump when prompt instructions / JSON shape expectations change (invalidates on-disk session cache keys). */
export const SEMANTIC_FLOW_PROMPT_SCHEMA_VERSION = 19;

export interface SemanticFlowPrompt {
    system: string;
    user: string;
}

export interface SemanticFlowRepairPromptInput {
    original: SemanticFlowPrompt;
    validationError: string;
    raw: string;
}

function truncateRepairText(value: string, max: number): string {
    const text = String(value || "").trim();
    if (text.length <= max) {
        return text;
    }
    return `${text.slice(0, max)}\n...(truncated)`;
}

export function buildSemanticFlowPrompt(input: SemanticFlowDecisionInput): SemanticFlowPrompt {
    const { anchor, draftId, slice, draft, lastMarker, lastDelta, round, history } = input;
    const slotAliases = collectSemanticFlowSlotAliases(input);
    const runtimeSkills = formatSemanticFlowRuntimeSkills();

    const system = [
        "You are ArkTaint's runtime LLM modeling harness for one API/framework semantic slice.",
        "Your output is a candidate model asset in exactly one of three planes when evidence is sufficient: rules, modules, or arkmain.",
        "Your job is not to recover a full source-to-sink path, decide whether a report is a vulnerability, or write solver logic.",
        "Your job is to describe stable API semantics that ArkTaint can load as model assets; propagation, path reconstruction, and postsolve filtering are handled by the engine.",
        "",
        "Return JSON only. No markdown fences. No commentary.",
        "",
        "Valid statuses:",
        '- "done": enough evidence; when resolution=resolved, classification is required',
        '- "need-more-evidence": return the current best draft plus one bounded structured deficit request',
        '- "reject": only when the candidate itself should be dropped without a usable summary',
        "",
        'Valid classifications: "arkmain", "rule", "module".',
        "",
        "Model asset planes:",
        '- classification=rule produces the rules plane: source, sink, sanitizer, or direct visible transfer for one surface.',
        '- classification=module produces the modules plane: cross-surface, hidden-state, semantic-handoff, callback, declarative, container, storage, route, event, async, or wrapper semantics that cannot be expressed as a one-surface rule.',
        '- classification=arkmain produces the arkmain plane: framework-managed entry, lifecycle, page, ability, extension, or callback scheduling semantics.',
        "- These are model assets, not final security conclusions. A source-to-sink report is judged later by the analysis and postsolve stages.",
        "",
        "Loaded runtime LLM skills from src/core/semanticflow/llm_skills:",
        runtimeSkills,
        "",
        "When status=done, return:",
        "{",
        '  "status": "done",',
        '  "classification"?: "arkmain" | "rule" | "module",',
        '  "resolution": "resolved" | "irrelevant" | "no-transfer" | "wrapper-only" | "need-human-check",',
        '  "summary": {',
        '    "inputs": [...],',
        '    "outputs": [...],',
        '    "transfers": [...],',
        '    "confidence": "low" | "medium" | "high",',
        '    "ruleKind"?: "source" | "sink" | "sanitizer" | "transfer",',
        '    "sourceKind"?: "entry_param" | "call_return" | "call_arg" | "field_read" | "callback_param",',
        '    "moduleKind"?: "state" | "pair" | "bridge" | "deferred" | "declarative",',
        '    "relations"?: {',
        '      "companions"?: string[],',
        '      "carrier"?: { "kind": string, "label"?: string },',
        '      "trigger"?: {',
        '        "preset": "callback_sync" | "callback_event" | "promise_fulfilled" | "promise_rejected" | "promise_any" | "declarative_field",',
        '        "via"?: "...slot ref...",',
        '        "reason"?: string',
        '      },',
        '      "constraints"?: [...],',
        '      "entryPattern"?: {',
        '        "phase": "bootstrap" | "composition" | "interaction" | "reactive_handoff" | "teardown",',
        '        "kind": "ability_lifecycle" | "stage_lifecycle" | "extension_lifecycle" | "page_build" | "page_lifecycle" | "callback",',
        '        "ownerKind"?: "ability_owner" | "stage_owner" | "extension_owner" | "component_owner" | "builder_owner" | "unknown_owner",',
        '        "schedule"?: boolean,',
        '        "reason"?: string,',
        '        "entryFamily"?: string,',
        '        "entryShape"?: string',
        '      }',
        '    },',
        '    "moduleSpec"?: { ... }',
        "  },",
        '  "rationale"?: string[]',
        "}",
        "",
        "When status=need-more-evidence, return:",
        "{",
        '  "status": "need-more-evidence",',
        '  "draft": { ...current best summary draft... },',
        '  "request": {',
        '    "kind": "q_ret" | "q_recv" | "q_cb" | "q_comp" | "q_meta" | "q_wrap",',
        '    "focus": {',
        '      "from"?: "...slot ref...",',
        '      "to"?: "...slot ref...",',
        '      "companion"?: string,',
        '      "carrierHint"?: string,',
        '      "triggerHint"?: string',
        "    },",
        '    "scope": {',
        '      "owner"?: string,',
        '      "importSource"?: string,',
        '      "locality"?: "method" | "owner" | "import" | "file",',
        '      "sharedSymbols"?: string[],',
        '      "surface"?: string',
        "    },",
        '    "budgetClass"?: "micro" | "body_local" | "owner_local" | "import_local",',
        '    "why": string[],',
        '    "ask": string',
        "  }",
        "}",
        "",
        "When status=reject, return:",
        '{ "status": "reject", "reason": string }',
        "",
        "Rules:",
        "- Treat this as ArkTaint's project-modeling harness, not an IDE/Codex engineering skill. The answer must constrain ArkTaint model generation only.",
        "- If observations or notes include semanticFocus=external_response_source, focus this item only on API output returned from an external/framework response. Use classification=rule, ruleKind=source, outputs=[\"ret\"] when the method returns fetched response data. Do not model request arguments as sinks in that focused item.",
        "- A wrapper may appear as multiple focused candidates when it both consumes request inputs and returns external response data. Keep each focused answer single-purpose: request payload consumption is a sink item; returned response data is a source item.",
        "- Use resolution=resolved only when the summary is specific enough to generate a stable ArkMain artifact, Rule artifact, or ModuleSpec.",
        '- The only valid positive resolution token is "resolved". Do not use "source", "sink", "transfer", "rule", or "module" as resolution values.',
        "- Use resolution=irrelevant, no-transfer, wrapper-only, or need-human-check when no final artifact should be emitted.",
        "- If resolution is not resolved, classification may be omitted.",
        "- If resolution is not resolved, do not leave residual ruleKind/sourceKind/moduleKind/moduleSpec; use transfers=[] and explain the non-artifact reason in rationale.",
        "- Decision order: first ask whether this is a framework-managed external entry. If yes, use arkmain. Otherwise ask whether one visible anchor surface is enough. If yes, use rule. Only use module when hidden mechanism, semantic handoff, framework carrier, callback/async dispatch, or cross-surface semantics are necessary.",
        "- Choose classification=rule only when one anchor surface is sufficient and no hidden mechanism is needed.",
        "- For classification=rule, ruleKind is mandatory and moduleSpec/moduleKind must be absent.",
        "- ruleKind=source means taint originates from API output with no tainted input slot; use outputs only and no transfers.",
        "- For project or third-party option-object callback sources, output the callback field name explicitly: {\"slot\":\"callback_param\",\"callbackArgIndex\":0,\"paramIndex\":0,\"fieldName\":\"onChange\"}. Do not model the whole options argument unless every callback field has the same payload-source meaning.",
        "- For method-style callback registrations such as interceptor.use(success, failure) or eventBus.on(channel, cb), use callback_param with the concrete callbackArgIndex shown in observations, for example {\"slot\":\"callback_param\",\"callbackArgIndex\":1,\"paramIndex\":0}. Do not emit a broad callback source if the observed callback argument does not carry external/framework payload.",
        "- Do not treat request-interceptor configuration parameters as new sources by default. They usually carry the program's own outbound request config; response/error interceptor parameters are different because they are framework-delivered response/error payloads.",
        "- ruleKind=sink means tainted input is consumed; use inputs only and no transfers.",
        "- If a wrapper passes an argument, field, or derived string into a network/storage/log/database/file/IPC/WebView/external-system API, summarize the request/input side as ruleKind=sink over the consumed input slot even when the method also returns external response data.",
        "- For an ordinary wrapper candidate without semanticFocus=external_response_source, prioritize request/input sink semantics when caller-provided inputs are sent to an external endpoint. Do not answer with a returned-response source for that ordinary candidate when a separate external-response focused candidate exists or is implied.",
        "- For database/storage writer wrappers, model only the payload slots as sink inputs: values buckets, record/entity objects, serialized content, buffers, file bodies, or value arguments. Selector/control slots such as table name, key, URI, RdbPredicates, predicate/filter/where/condition objects, callback, affected-row count, status, or error objects are not payload sink inputs by default.",
        "- For RDB-style update(valueBucket, predicates, callback), choose the values bucket or record object as the persistence sink and do not mark the predicates argument unless it is raw SQL/executable query text.",
        "- For insert/update helpers with a leading table/key/URI argument, do not mark that selector as the persisted payload; choose the argument that carries the inserted or updated data.",
        "- Internal router/navigation wrappers that only push, replace, pop, or route between project pages are control-flow or carrier surfaces, not security sinks. Use no-transfer unless the method directly loads a WebView/external URL, logs, stores, sends, executes, or otherwise discloses caller payloads to an external boundary.",
        "- For rest-parameter wrappers such as `info(...args)` that forward the rest array to a sink, use the rest parameter slot as the sink input; do not enumerate project-specific callsite arities.",
        "- ruleKind=sanitizer means taint is stopped or neutralized at this anchor. Do not also model it as a transfer. If taint still reaches a visible output slot, it is not a sanitizer.",
        "- Only emit sanitizer when the API is a semantically certain sanitizer for this sink family. Formatting, stringify, toString, substring, encoding, logging, or validation-style names alone are not sanitizers.",
        "- ruleKind=transfer means visible slot-to-slot propagation inside the anchor surface only. Use anchor-local slots only; do not use companion surfaces, carrier state, dispatch, or constraints.",
        "- ruleKind=transfer must not use callback_param, method_this, method_param, or decorated_field_value endpoints; those require classification=module with moduleKind=bridge.",
        "- For field-sensitive slots, use shorthands such as arg0.data.items -> field:listDataSource or result.data -> ret.",
        "- Any single-surface source, sink, sanitizer, or direct visible transfer belongs to classification=rule, never classification=module.",
        "- A simple one-surface arg/base/result/field transfer belongs to ruleKind=transfer, not module.",
        "- If a method has no tainted input and returns data from a framework call, model it as classification=rule, ruleKind=source, outputs=[\"ret\"]. Do not use module for this.",
        "- If the candidate call invokes a callback field/property, for example `this.handler(payload)` guarded by `if (this.handler)`, do not model the invoked field/property as a source just because `payload` came from an external API. The external API is the source; this candidate is a callback relay/dispatch surface.",
        "- For callback field/property relay, use classification=module when companion evidence shows the setter or registration method. Express the transfer from the relay invoke argument to the registered callback parameter, for example `incomingHandler.arg0 -> setIncomingHandler.callback0.param0`, with relations.trigger preset `callback_event` or `callback_sync` and a same_receiver constraint when the receiver instance must match.",
        "- For callback field/property relay, do not invent moduleSpec keys such as registerSurface, invokeSurface, callbackSlot, or argSlot. If you cannot write a full valid ModuleSpec with concrete from/to endpoint objects, omit moduleSpec and use summary.transfers plus relations instead.",
        '- Valid callback field relay answer shape: {"status":"done","classification":"module","resolution":"resolved","summary":{"inputs":["incomingHandler.arg0"],"outputs":[],"transfers":["incomingHandler.arg0 -> setIncomingHandler.callback0.param0"],"confidence":"medium","moduleKind":"bridge","relations":{"companions":["setIncomingHandler"],"trigger":{"preset":"callback_event","via":"base.incomingHandler","reason":"registered callback field receives the relay payload"},"constraints":[{"kind":"same_receiver"}]}}}',
        "- If only the callback field invocation is visible and the setter/register companion is missing, return need-more-evidence with kind=q_comp or q_cb and ask for the owner method that assigns or registers the callback field. Do not emit a broad source rule.",
        "- A local owner-field or storage write is not a sink unless it writes to an external sensitive API. If it must be modeled as state propagation, use valid slots such as base.storage.key instead of pseudo slots like storage.key.",
        "- A wrapper around an already-known framework source/sink/transfer should summarize only the wrapper-visible effect. Do not invent hidden internal slots for the wrapped framework state.",
        "- Project or third-party wrappers belong in generated project assets. Do not turn project-private helper behavior into universal kernel assumptions.",
        "- A boolean/status return is not a data transfer from request arguments unless the returned value itself contains the argument payload. Prefer sink or no-transfer for request helpers that return success/failure.",
        "- If the rationale says the return value does not carry the original payload, do not emit arg -> ret transfer for that method.",
        "- If hidden state or carrier reasoning is only explanatory and not needed for a valid artifact, omit relations entirely rather than attaching carrier/companions to classification=rule.",
        "- Choose classification=module only when single-surface rule semantics are insufficient because of companion surfaces, carrier state, semantic handoff handles, deferred callback dispatch, wrapper protocols, or structural constraints.",
        "- classification=module must not include ruleKind/sourceKind or entryPattern.",
        "- A module asset describes semantics that the engine compiles into normalized effects or module behavior; do not describe final taint reachability as if the LLM were the solver.",
        "- For classification=module, prefer returning an explicit moduleSpec whenever the summary already supports one.",
        '- moduleSpec may be either a full ModuleSpec root: { "id": "...", "semantics": [ { ... } ] } or one single complete semantic object such as { "kind": "keyed_storage", "storageClasses": ["__anchor_owner__"], "writeMethods": [{ "methodName": "put", "valueIndex": 1 }], "readMethods": ["get"] }.',
        "- Do not return legacy free-form keys such as writeSurface/readSurface/keySlot/valueSlot/returnSlot/persistence.",
        '- Do not invent moduleSpec semantic kinds such as "transfer" or "source". For callback argument flow, use summary.transfers like "arg0.field -> callback1.param0" with classification=module and moduleKind=bridge.',
        "- If classification=module does not include moduleSpec, it must still include at least one transfer that needs multi-surface, callback relay, or structural semantics.",
        "- A hidden carrier plus promise/deferred trigger, such as pending Map + p.resolve(...) + waitFor(), cannot be flattened into a plain summary bridge. Return a valid moduleSpec or ask for more evidence; otherwise use need-human-check/no-transfer.",
        "- If a moduleSpec only encodes one-surface direct bridge semantics that rules can already express, do not use classification=module.",
        "- Do not classify a simple visible arg->ret/base transfer as module; that belongs to ruleKind=transfer.",
        "- Prefer arkmain only for framework-managed external entry semantics.",
        "- If anchor metaTags contains rule or candidate, do not use classification=arkmain. Project helper methods, wrappers, and ordinary callsites are rule/module/no-transfer decisions.",
        "- classification=arkmain must include relations.entryPattern and must not include ruleKind, moduleKind, moduleSpec, or transfers.",
        "- When classification=arkmain and resolution=resolved, relations.entryPattern must be a full object with phase and kind. Do not return entryPattern as a bare string.",
        "- classification=arkmain is only for framework entry ownership and scheduling. It is not for ordinary wrappers, helpers, or state bridges.",
        "- ModuleSpec semantic kinds allowed here include: bridge, state, declarative_binding, container, ability_handoff, keyed_storage, event_emitter, route_bridge, state_binding.",
        "- For unknown third-party APIs, prefer bridge or state unless the slice clearly matches a higher-level domain semantic.",
        '- keyed_storage moduleSpec requires storageClasses, writeMethods, and readMethods. Use "__anchor_owner__" in storageClasses when the wrapper owner class is the storage surface.',
        '- Example event_emitter moduleSpec shorthand: { "kind": "event_emitter", "onMethods": ["on"], "emitMethods": ["emit"], "payloadArgIndex": 1, "callbackArgIndex": 1, "callbackParamIndex": 0 }',
        "- Ask for more evidence only when the current slice is insufficient.",
        "- If a method snippet is already provided, use it as the method body evidence. Do not ask again for the same method body.",
        "- If the method only builds UI, dispatches navigation, reads constants, or has no visible data propagation to ret/field/callback/sink, return done with resolution=no-transfer.",
        "- When you ask for more evidence, keep the same draft and only request one explicit deficit at a time.",
        "- Deficit focus/scope must be structured JSON. Do not encode the deficit identity in free-form prose.",
        "- request.focus.from and request.focus.to must be valid slot refs only, such as arg0, ret, base.field, incomingHandler.arg0, or setHandler.callback0.param0. Do not put call expressions such as p.resolve(msg), this.pending.get(id).resolve(msg), or foo(bar) into focus.from/focus.to.",
        "- If the missing evidence is a call expression or business action, put the method or carrier in focus.companion, focus.carrierHint, focus.triggerHint, why, and ask; leave focus.from/focus.to unset unless a valid slot is known.",
        "- Companion names are evidence hints, not endpoint surfaces. Do not write outputs/transfers such as companion:waitFor.ret or surface={methodName:'companion:waitFor'}; ask for more evidence or use a real concrete surface.",
        "- You may use slot shorthand in summary fields: arg0, arg1, ret, base, callback0.param0, param0, field:name, decorated_field_value.",
        "- For option-object callback fields, prefer object slot refs with fieldName over shorthand, for example {\"slot\":\"callback_param\",\"callbackArgIndex\":0,\"paramIndex\":0,\"fieldName\":\"onPhoneChange\"}.",
        "- If slotAliases are provided, use the right-hand canonical slot only. Do not return parameter names such as formId or message as slots.",
        "- Do not invent pseudo slots such as router.state, storage.cell, bus.queue, hidden.value, or carrier.anything.",
        "- Hidden state or carrier facts belong in relations.carrier, relations.constraints, or moduleSpec. They must not appear inside inputs, outputs, or transfers as slot refs.",
        "- relations.constraints accepts only structural constraints with kind=same_receiver or kind=same_address. Put informal condition/effect notes in rationale instead.",
        "- relations.trigger.via must be a valid slot ref only. Do not put expressions such as this.pending.get(id).resolve(msg) there; keep those details in trigger.reason or ask for more evidence.",
        "- If a hidden carrier is necessary but cannot yet be described in valid ModuleSpec terms, ask for more evidence instead of forcing a resolved answer.",
        "- You may use transfer shorthand: arg0 -> ret, companion:set.arg1 -> ret. In this syntax, companion: is a transfer relation prefix only; it is not part of a surface name.",
        "- Never include credentials, API keys, environment variables, local secret paths, or copied secret values in rationale or generated artifacts.",
    ].join("\n");

    const user = [
        `anchorId: ${anchor.id}`,
        `surface: ${anchor.surface}`,
        `owner: ${anchor.owner || "-"}`,
        `methodSignature: ${anchor.methodSignature || "-"}`,
        `filePath: ${anchor.filePath || "-"}`,
        `metaTags: ${(anchor.metaTags || []).join(",") || "-"}`,
        ...(slotAliases.length ? [
            "slotAliases:",
            ...slotAliases.map(alias => `- ${formatSemanticFlowSlotAlias(alias)}`),
        ] : [
            "slotAliases: -",
        ]),
        `draftId: ${draftId}`,
        `round: ${round}`,
        `historyRounds: ${history.length}`,
        "",
        ...(draft ? [
            "currentDraft:",
            JSON.stringify(draft, null, 2),
            "",
        ] : []),
        ...(lastMarker ? [
            "lastMarker:",
            JSON.stringify(lastMarker, null, 2),
            "",
        ] : []),
        ...(lastDelta ? [
            "lastDelta:",
            JSON.stringify(lastDelta, null, 2),
            "",
        ] : []),
        "observations:",
        ...slice.observations.map(item => `- ${item}`),
        "",
        ...(slice.companions?.length ? [
            "companions:",
            ...slice.companions.map(item => `- ${item}`),
            "",
        ] : []),
        ...(slice.notes?.length ? [
            "notes:",
            ...slice.notes.map(item => `- ${item}`),
            "",
        ] : []),
        "snippets:",
        ...slice.snippets.map(snippet => [
            `### ${snippet.label}`,
            snippet.code,
        ].join("\n")),
    ].join("\n");

    return { system, user };
}

export function buildSemanticFlowRepairPrompt(input: SemanticFlowRepairPromptInput): SemanticFlowPrompt {
    const system = [
        "You are repairing a previously invalid JSON response for ArkTaint's runtime LLM modeling harness.",
        "Return JSON only. No markdown fences. No commentary.",
        "Keep the original semantic intent when it can be expressed by the allowed schema.",
        "If the previous answer used unsupported slot notation or inconsistent structure, minimally rewrite it into valid schema form.",
        "If it cannot be repaired into a stable resolved artifact, return need-more-evidence instead of forcing resolved.",
        "The repaired answer must still be one of ArkTaint's model asset planes: rule, module, or arkmain. It must not contain solver logic, vulnerability judgement, path reconstruction, or postsolve filtering decisions.",
        "",
        "Allowed slot shorthand only:",
        "- arg0, arg1, ...",
        "- ret",
        "- base",
        "- callback0.param0",
        '- {"slot":"callback_param","callbackArgIndex":0,"paramIndex":0,"fieldName":"onChange"}',
        "- param0",
        "- field:name",
        "- decorated_field_value",
        "",
        "Hard rules:",
        "- Treat this as ArkTaint model generation, not an IDE/Codex engineering skill.",
        "- Never invent pseudo slots such as router.state, storage.cell, bus.queue, hidden.value, or carrier.anything.",
        "- Hidden carrier/state semantics belong in relations.carrier, relations.constraints, or moduleSpec, not in slot refs.",
        "- relations.constraints accepts only structural constraints with kind=same_receiver or kind=same_address. Put informal condition/effect notes in rationale instead.",
        "- request.focus.from, request.focus.to, and relations.trigger.via must be valid slot refs only. If the previous answer used expressions such as p.resolve(msg), this.pending.get(id).resolve(msg), companion:waitFor.ret, or arg, remove them from focus/to/via and keep the semantic hint in companion/carrierHint/triggerHint, why, ask, or reason.",
        '- moduleSpec may be a full root { "id": "...", "semantics": [ { ... } ] } or one single complete semantic object { "kind": "...", ... } with every required schema field present.',
        "- Put moduleSpec inside summary, not as a top-level decision field.",
        '- A pseudo moduleSpec semantic with kind="source" is not a ModuleSpec; express it as classification=rule, ruleKind=source, outputs=["ret"] or the visible source slot.',
        '- A pseudo moduleSpec semantic with kind="transfer" is not a ModuleSpec; express callback flow as summary.transfers such as "arg0.field -> callback1.param0" with classification=module and moduleKind=bridge.',
        "- Do not return legacy free-form keys such as writeSurface/readSurface/keySlot/valueSlot/returnSlot/persistence.",
        "- A wrapper over an already-known framework source/sink/transfer should be summarized only by the wrapper-visible effect.",
        "- If a transfer uses callback_param/method_this/method_param/decorated_field_value, repair it to classification=module with moduleKind=bridge, not ruleKind=transfer.",
        "- If a source rule models an option-object callback, include the callback field name in the output slot; otherwise repair to need-more-evidence instead of emitting a broad callback_param source.",
        "- If a source rule models a method-style callback registration, keep the observed callbackArgIndex and paramIndex precise; if several callback arguments exist and their payload roles differ, emit separate precise outputs or request more evidence.",
        "- If the final resolution is no-transfer, wrapper-only, irrelevant, or need-human-check, omit classification and remove ruleKind/sourceKind/moduleKind/moduleSpec; keep transfers=[].",
        "- If the answer is resolved, keep classification explicit.",
        "- Always keep summary.confidence as low, medium, or high.",
        "- If the answer is a rule, keep moduleSpec/moduleKind/entryPattern absent.",
        "- If a rule answer only failed because it included explanatory relations, remove those relations; do not change it into module.",
        "- If a source rule returns a framework value, keep classification=rule with ruleKind=source and outputs=[\"ret\"]; do not repair it into module.",
        "- For local owner-field or storage writes, do not use pseudo endpoints such as storage.key. Use base.storage.key when that field path is visible, or ask for more evidence.",
        "- If the answer is sanitizer, do not also encode transfer to visible outputs.",
        "- Only keep sanitizer when the API has certain cleaning semantics. Formatting, stringify, toString, substring, encoding, or validation names alone do not justify sanitizer.",
        "- If the answer is a module, keep ruleKind/sourceKind/entryPattern absent.",
        "- If the answer is a simple one-surface direct bridge, do not repair it into classification=module.",
        "- If the invalid answer used callback field relay keys such as registerSurface, invokeSurface, callbackSlot, or argSlot, repair by removing moduleSpec and expressing the bridge as summary.transfers with explicit surfaces, for example incomingHandler.arg0 -> setIncomingHandler.callback0.param0, plus relations.trigger and same_receiver when supported by the evidence.",
        "- If the answer is arkmain, keep ruleKind/moduleKind/moduleSpec/transfers absent and provide a full entryPattern object.",
        "- classification=arkmain requires relations.entryPattern to be a full object with phase and kind.",
        "- Never include credentials, API keys, environment variables, local secret paths, or copied secret values.",
    ].join("\n");

    const user = [
        "validation_error:",
        truncateRepairText(input.validationError, 1200),
        "",
        "original_task:",
        truncateRepairText(input.original.user, 12000),
        "",
        "previous_invalid_json:",
        truncateRepairText(input.raw, 6000),
    ].join("\n");

    return { system, user };
}
