import type { ArkMainSpec } from "../entry/arkmain/ArkMainSpec";
import type {
    ModuleConstraint,
    ModuleDispatch,
    ModuleEndpoint,
    ModuleSpec,
} from "../kernel/contracts/ModuleSpec";
import { canonicalizeModuleSpec } from "../kernel/contracts/ModuleSpecCanonicalizer";
import { validateModuleSpecOrThrow } from "../kernel/contracts/ModuleSpecValidator";
import type {
    RuleEndpoint,
    RuleEndpointOrRef,
    RuleMatch,
    RuleScopeConstraint,
    SinkRule,
    SanitizerRule,
    SourceRule,
    SourceRuleKind,
    TaintRuleSet,
    TransferRule,
} from "../rules/RuleSchema";
import type {
    SemanticFlowAnalysisAugment,
    SemanticFlowAnchor,
    SemanticFlowArkMainArtifact,
    SemanticFlowArtifact,
    SemanticFlowArtifactClass,
    SemanticFlowEngineAugment,
    SemanticFlowItemResult,
    SemanticFlowModuleArtifact,
    SemanticFlowRuleArtifact,
    SemanticFlowSummary,
    SemanticFlowSurfaceSlotRef,
} from "./SemanticFlowTypes";

export function classifySemanticFlowSummary(
    anchor: SemanticFlowAnchor,
    summary: SemanticFlowSummary,
    hint?: SemanticFlowArtifactClass,
): SemanticFlowArtifactClass | undefined {
    if (!hint) {
        return undefined;
    }
    if (hint === "arkmain" && isArkMainEligibleAnchor(anchor) && isEntryLike(summary)) {
        return "arkmain";
    }
    if (hint === "rule" && isRuleLike(summary)) {
        return "rule";
    }
    if (hint === "module" && isModuleLike(summary)) {
        return "module";
    }
    return undefined;
}

function isArkMainEligibleAnchor(anchor: SemanticFlowAnchor): boolean {
    return Boolean(anchor.arkMainSelector);
}

export function buildSemanticFlowArtifact(
    anchor: SemanticFlowAnchor,
    summary: SemanticFlowSummary,
    classification: SemanticFlowArtifactClass,
): SemanticFlowArtifact {
    if (classification === "arkmain") {
        return buildArkMainArtifact(anchor, summary);
    }
    if (classification === "module") {
        return buildModuleArtifact(anchor, summary);
    }
    return buildRuleArtifact(anchor, summary);
}

export function buildSemanticFlowAnalysisAugment(items: SemanticFlowItemResult[]): SemanticFlowAnalysisAugment {
    const ruleSet: TaintRuleSet = {
        schemaVersion: "2.0",
        meta: {
            name: "semanticflow-artifacts",
            description: "Generated by unified semantic flow pipeline.",
            updatedAt: new Date().toISOString().slice(0, 10),
        },
        sources: [],
        sinks: [],
        sanitizers: [],
        transfers: [],
    };
    const moduleSpecs: ModuleSpec[] = [];
    const arkMainSpecs: ArkMainSpec[] = [];

    for (const item of items) {
        if (!item.artifact) {
            continue;
        }
        if (item.artifact.kind === "rule") {
            ruleSet.sources.push(...(item.artifact.ruleSet.sources || []));
            ruleSet.sinks.push(...(item.artifact.ruleSet.sinks || []));
            ruleSet.sanitizers!.push(...(item.artifact.ruleSet.sanitizers || []));
            ruleSet.transfers.push(...(item.artifact.ruleSet.transfers || []));
            continue;
        }
        if (item.artifact.kind === "module") {
            moduleSpecs.push(item.artifact.moduleSpec);
            continue;
        }
        arkMainSpecs.push(item.artifact.spec);
    }

    return consolidateSemanticFlowAnalysisAugmentByFootprint({
        ruleSet,
        moduleSpecs,
        arkMainSpecs,
    });
}

export function mergeSemanticFlowAnalysisAugments(
    augments: SemanticFlowAnalysisAugment[],
): SemanticFlowAnalysisAugment {
    const ruleSet: TaintRuleSet = {
        schemaVersion: "2.0",
        meta: {
            name: "semanticflow-artifacts",
            description: "Merged semantic flow artifacts.",
            updatedAt: new Date().toISOString().slice(0, 10),
        },
        sources: [],
        sinks: [],
        sanitizers: [],
        transfers: [],
    };
    const moduleSpecs: ModuleSpec[] = [];
    const arkMainSpecs: ArkMainSpec[] = [];

    for (const augment of augments) {
        ruleSet.sources.push(...(augment.ruleSet.sources || []));
        ruleSet.sinks.push(...(augment.ruleSet.sinks || []));
        ruleSet.sanitizers!.push(...(augment.ruleSet.sanitizers || []));
        ruleSet.transfers.push(...(augment.ruleSet.transfers || []));
        moduleSpecs.push(...(augment.moduleSpecs || []));
        arkMainSpecs.push(...(augment.arkMainSpecs || []));
    }

    return consolidateSemanticFlowAnalysisAugmentByFootprint({
        ruleSet,
        moduleSpecs,
        arkMainSpecs,
    });
}

export function buildSemanticFlowEngineAugment(augment: SemanticFlowAnalysisAugment): SemanticFlowEngineAugment {
    return {
        sourceRules: augment.ruleSet.sources || [],
        sinkRules: augment.ruleSet.sinks || [],
        sanitizerRules: augment.ruleSet.sanitizers || [],
        transferRules: augment.ruleSet.transfers || [],
        moduleSpecs: augment.moduleSpecs,
        arkMainSpecs: augment.arkMainSpecs,
    };
}

function isEntryLike(summary: SemanticFlowSummary): boolean {
    return Boolean(summary.relations?.entryPattern);
}

function isModuleLike(summary: SemanticFlowSummary): boolean {
    if (summary.moduleSpec || summary.moduleKind) {
        return true;
    }
    return Boolean(
        (summary.relations?.companions && summary.relations.companions.length > 0)
        || summary.relations?.carrier
        || summary.relations?.trigger
        || (summary.relations?.constraints && summary.relations.constraints.length > 0),
    );
}

function isRuleLike(summary: SemanticFlowSummary): boolean {
    if (summary.ruleKind) {
        return true;
    }
    return summary.transfers.length > 0 || summary.inputs.length > 0 || summary.outputs.length > 0;
}

function buildArkMainArtifact(anchor: SemanticFlowAnchor, summary: SemanticFlowSummary): SemanticFlowArkMainArtifact {
    if (!anchor.arkMainSelector) {
        throw new Error(`arkmain artifact requires anchor.arkMainSelector: ${anchor.id}`);
    }
    const entry = summary.relations?.entryPattern;
    if (!entry) {
        throw new Error(`arkmain summary requires relations.entryPattern: ${anchor.id}`);
    }
    return {
        kind: "arkmain",
        spec: {
            enabled: true,
            description: `Generated by semantic flow pipeline for ${anchor.surface}.`,
            selector: anchor.arkMainSelector,
            entryPattern: {
                phase: entry.phase,
                kind: entry.kind,
                ownerKind: entry.ownerKind,
                schedule: entry.schedule ?? true,
                reason: entry.reason || `semanticflow:${anchor.surface}`,
                entryFamily: entry.entryFamily,
                entryShape: entry.entryShape,
            },
        },
    };
}

function buildRuleArtifact(anchor: SemanticFlowAnchor, summary: SemanticFlowSummary): SemanticFlowRuleArtifact {
    const signature = requireAnchorSignature(anchor);
    const idBase = sanitizeId(`semanticflow.${anchor.id}`);
    const ruleKind = inferRuleKind(summary);

    const ruleSet: TaintRuleSet = {
        schemaVersion: "2.0",
        meta: {
            name: `${idBase}.rules`,
            description: `Generated from semantic flow pipeline for ${anchor.surface}.`,
            updatedAt: new Date().toISOString().slice(0, 10),
        },
        sources: [],
        sinks: [],
        sanitizers: [],
        transfers: [],
    };

    if (ruleKind === "source") {
        const targets = filterSurfaceSlotRefsByAnchorArity(anchor, summary.outputs);
        if (targets.length === 0) {
            throw new Error(`source rule summary requires at least one output slot: ${anchor.id}`);
        }
        ruleSet.sources.push(...targets.map((target, index) =>
            buildSourceRule(anchor, signature, sourceRuleId(idBase, index), summary, target),
        ));
        return { kind: "rule", ruleSet };
    }

    if (ruleKind === "sink") {
        const rawTargets = summary.inputs.length > 0 ? summary.inputs : summary.outputs;
        const targets = filterSemanticFlowSinkTargets(anchor, filterSurfaceSlotRefsByAnchorArity(anchor, rawTargets));
        if (targets.length === 0) {
            throw new Error(`sink rule summary requires at least one input/output slot: ${anchor.id}`);
        }
        const scope = buildInvocationRuleScope(anchor, signature);
        ruleSet.sinks.push(...targets.map((target, index) => ({
            id: sinkRuleId(idBase, index),
            enabled: true,
            description: `Generated sink rule for ${anchor.surface}.`,
            tags: ["semanticflow", "llm"],
            match: buildRuleMatch(anchor, signature),
            ...(scope ? { scope } : {}),
            target: sinkTargetEndpoint(anchor, target),
        } satisfies SinkRule)));
        return { kind: "rule", ruleSet };
    }

    if (ruleKind === "sanitizer") {
        const targets = filterSurfaceSlotRefsByAnchorArity(anchor, summary.inputs.length > 0 ? summary.inputs : summary.outputs);
        if (targets.length === 0) {
            throw new Error(`sanitizer rule summary requires at least one input/output slot: ${anchor.id}`);
        }
        const scope = buildInvocationRuleScope(anchor, signature);
        ruleSet.sanitizers!.push(...targets.map((target, index) => ({
            id: sanitizerRuleId(idBase, index),
            enabled: true,
            description: `Generated sanitizer rule for ${anchor.surface}.`,
            tags: ["semanticflow", "llm"],
            match: buildRuleMatch(anchor, signature),
            ...(scope ? { scope } : {}),
            target: toRuleEndpoint(target),
        } satisfies SanitizerRule)));
        return { kind: "rule", ruleSet };
    }

    if (summary.transfers.length === 0) {
        throw new Error(`transfer rule summary requires at least one transfer: ${anchor.id}`);
    }
    const scope = buildInvocationRuleScope(anchor, signature);
    const transfers = summary.transfers.filter(transfer =>
        isSurfaceSlotRefAllowedByAnchorArity(anchor, transfer.from)
        && isSurfaceSlotRefAllowedByAnchorArity(anchor, transfer.to),
    );
    if (transfers.length === 0) {
        throw new Error(`transfer rule summary requires at least one valid transfer endpoint: ${anchor.id}`);
    }
    ruleSet.transfers.push(...transfers.map((transfer, index) => ({
        id: transferRuleId(idBase, index),
        enabled: true,
        description: `Generated transfer rule for ${anchor.surface}.`,
        tags: ["semanticflow", "llm"],
        match: buildRuleMatch(anchor, signature),
        ...(scope ? { scope } : {}),
        from: toRuleEndpoint(transfer.from),
        to: toRuleEndpoint(transfer.to),
    } satisfies TransferRule)));
    return { kind: "rule", ruleSet };
}

function filterSurfaceSlotRefsByAnchorArity(
    anchor: SemanticFlowAnchor,
    refs: SemanticFlowSurfaceSlotRef[],
): SemanticFlowSurfaceSlotRef[] {
    return refs.filter(ref => isSurfaceSlotRefAllowedByAnchorArity(anchor, ref));
}

function isSurfaceSlotRefAllowedByAnchorArity(
    anchor: SemanticFlowAnchor,
    ref: SemanticFlowSurfaceSlotRef,
): boolean {
    if (ref.slot !== "arg" || typeof ref.index !== "number") {
        return true;
    }
    const signature = anchor.methodSignature || anchor.method?.getSignature?.()?.toString?.() || "";
    if (!hasSignatureParameterList(signature)) {
        return true;
    }
    return ref.index >= 0 && ref.index < parseSignatureParameterTypes(signature).length;
}

function buildRuleMatch(anchor: SemanticFlowAnchor, signature: string): RuleMatch {
    if (!shouldUseScopedMethodRule(anchor, signature)) {
        return {
            kind: "signature_equals",
            value: signature,
        };
    }
    const methodName = String(anchor.surface || "").trim();
    if (!methodName) {
        throw new Error(`unknown anchor signature requires a stable surface method name: ${anchor.id}`);
    }
    const match: RuleMatch = {
        kind: "method_name_equals",
        value: methodName,
    };
    if (hasSignatureParameterList(signature)) {
        match.argCount = parseSignatureParameterTypes(signature).length;
    }
    if (anchor.typeHint) {
        match.typeHint = anchor.typeHint;
    }
    if ((anchor.callbackProperties || []).length > 0) {
        return match;
    }
    if ((anchor.metaTags || []).includes("instance")) {
        match.invokeKind = "instance";
    } else if ((anchor.metaTags || []).includes("static")) {
        match.invokeKind = "static";
    }
    return match;
}

function shouldUseScopedMethodRule(anchor: SemanticFlowAnchor, signature: string): boolean {
    if (isUnknownSemanticFlowSignature(signature)) {
        return true;
    }
    const tags = anchor.metaTags || [];
    if (tags.includes("rule") && /\bUnknown\b/.test(signature)) {
        return true;
    }
    return isSemanticFlowModelingCandidate(tags)
        && isProjectLocalSemanticFlowAnchor(anchor, signature);
}

function isSemanticFlowModelingCandidate(tags: string[]): boolean {
    return tags.includes("candidate")
        || tags.includes("api-modeling-candidate");
}

function isUnknownSemanticFlowSignature(signature: string): boolean {
    const text = String(signature || "").trim().toLowerCase();
    return !text
        || text.includes("%unk")
        || text.startsWith("@unk")
        || text.includes("@unk/")
        || /(^|[,(<\s])unknown([,)>\s]|$)/i.test(signature);
}

function hasSignatureParameterList(signature: string): boolean {
    const text = String(signature || "");
    return text.lastIndexOf("(") >= 0 && text.lastIndexOf(")") > text.lastIndexOf("(");
}

function buildInvocationRuleScope(anchor: SemanticFlowAnchor, signature: string): RuleScopeConstraint | undefined {
    if (!shouldUseScopedMethodRule(anchor, signature)) {
        return undefined;
    }
    const className = stableScopeToken(extractAnchorOwnerClassName(anchor));
    if (className) {
        return {
            className: {
                mode: "equals",
                value: className,
            },
        };
    }
    const file = stableSourceFileScope(anchor.filePath || extractFilePathFromSignatureLike(signature));
    if (file) {
        return {
            file: {
                mode: "contains",
                value: file,
            },
        };
    }
    return undefined;
}

function stableScopeToken(value: string | undefined): string | undefined {
    const text = String(value || "").trim();
    if (!text || text.includes("%unk") || text.startsWith("%")) {
        return undefined;
    }
    return text;
}

function stableSourceFileScope(value: string | undefined): string | undefined {
    const text = String(value || "").replace(/\\/g, "/").trim();
    if (!text || text.includes("%unk")) {
        return undefined;
    }
    const normalized = text
        .replace(/^@/, "")
        .replace(/^entry\/src\/main\/ets\//, "")
        .replace(/^src\/main\/ets\//, "")
        .replace(/^ets\//, "");
    return normalized || undefined;
}

function isProjectLocalSemanticFlowAnchor(anchor: SemanticFlowAnchor, signature: string): boolean {
    const file = stableSourceFileScope(anchor.filePath || extractFilePathFromSignatureLike(signature));
    if (!file) {
        return false;
    }
    const normalized = file.replace(/\\/g, "/").toLowerCase();
    if (/(^|\/)(node_modules|oh_modules|interface_sdk-js|arkanalyzer)(\/|$)/i.test(normalized)) {
        return false;
    }
    return /\.(ets|ts|js|mjs|cjs)$/i.test(normalized)
        || normalized.startsWith("entry/src/main/ets/")
        || normalized.startsWith("src/main/ets/")
        || normalized.startsWith("ets/");
}

function extractFilePathFromSignatureLike(signature: string): string | undefined {
    const match = String(signature || "").match(/^@([^:]+):/);
    return match?.[1];
}

function buildSourceRule(
    anchor: SemanticFlowAnchor,
    signature: string,
    ruleId: string,
    summary: SemanticFlowSummary,
    target: SemanticFlowSurfaceSlotRef,
): SourceRule {
    const sourceKind = normalizeSourceKindForTarget(summary.sourceKind, target);
    const callbackArgIndexes = target.slot === "callback_param"
        ? [target.callbackArgIndex ?? 0]
        : undefined;
    const callbackFieldNames = resolveSourceRuleCallbackFieldNames(anchor, target);
    const invocationScope = buildInvocationRuleScope(anchor, signature);
    const useCallerScope = shouldScopeCallbackRegistrationByCaller(anchor, signature, sourceKind);
    return {
        id: ruleId,
        enabled: true,
        description: `Generated source rule for ${signature}.`,
        tags: ["semanticflow", "llm"],
        match: buildRuleMatch(anchor, signature),
        ...(useCallerScope && invocationScope ? { scope: invocationScope } : {}),
        ...(!useCallerScope && invocationScope ? { calleeScope: invocationScope } : {}),
        sourceKind,
        target: toSourceRuleTarget(target),
        callbackArgIndexes,
        ...(callbackFieldNames ? { callbackFieldNames } : {}),
    };
}

function shouldScopeCallbackRegistrationByCaller(
    anchor: SemanticFlowAnchor,
    signature: string,
    sourceKind: string,
): boolean {
    if (sourceKind !== "callback_param") {
        return false;
    }
    if (!isUnknownSemanticFlowSignature(signature)) {
        return false;
    }
    return !!(anchor.typeHint && (anchor.callbackArgIndexes || []).length > 0);
}

function resolveSourceRuleCallbackFieldNames(
    anchor: SemanticFlowAnchor,
    target: SemanticFlowSurfaceSlotRef,
): string[] | undefined {
    if (target.slot !== "callback_param") {
        return undefined;
    }
    const fromTarget = normalizeCallbackFieldNames([
        target.fieldName,
        ...fieldPathHeadCandidates(target.fieldPath),
    ]);
    if (fromTarget.length > 0) {
        return fromTarget;
    }
    const anchorFields = normalizeCallbackFieldNames(anchor.callbackProperties || []);
    if (anchorFields.length === 1) {
        return anchorFields;
    }
    if (anchorFields.length > 1) {
        throw new Error(`callback_param source for ${anchor.id} must specify fieldName when multiple callbackProperties are available: ${anchorFields.join(",")}`);
    }
    return undefined;
}

function fieldPathHeadCandidates(fieldPath: any): string[] {
    if (Array.isArray(fieldPath) && fieldPath.length > 0) {
        return [String(fieldPath[0] || "")];
    }
    const parts = Array.isArray(fieldPath?.parts) ? fieldPath.parts : [];
    for (const part of parts) {
        if (part?.kind === "literal" && typeof part.value === "string" && part.value.trim()) {
            return [part.value];
        }
    }
    return [];
}

function normalizeCallbackFieldNames(values: Array<string | undefined>): string[] {
    const out = new Set<string>();
    for (const raw of values) {
        const text = String(raw || "").trim();
        if (text) out.add(text);
    }
    return [...out.values()].sort((a, b) => a.localeCompare(b));
}

function inferSourceKind(target: SemanticFlowSurfaceSlotRef) {
    if (target.slot === "callback_param") return "callback_param" as const;
    if (target.slot === "result") return "call_return" as const;
    if (target.slot === "field_load") return "field_read" as const;
    if (target.slot === "arg") return "entry_param" as const;
    throw new Error(`cannot infer sourceKind from slot ${target.slot}`);
}

function normalizeSourceKindForTarget(
    preferred: SourceRuleKind | undefined,
    target: SemanticFlowSurfaceSlotRef,
): SourceRuleKind {
    const inferred = inferSourceKind(target);
    if (!preferred) {
        return inferred;
    }
    if (target.slot === "result" && preferred !== "call_return") {
        return "call_return";
    }
    if (target.slot === "callback_param" && preferred !== "callback_param") {
        return "callback_param";
    }
    if (target.slot === "field_load" && preferred !== "field_read") {
        return "field_read";
    }
    if (target.slot === "arg" && preferred !== "entry_param") {
        return "entry_param";
    }
    return preferred;
}

function toSourceRuleTarget(target: SemanticFlowSurfaceSlotRef): RuleEndpointOrRef {
    if (target.slot === "callback_param") {
        return { endpoint: `arg${target.paramIndex ?? 0}` as RuleEndpoint };
    }
    return toRuleEndpoint(target);
}

function inferRuleKind(summary: SemanticFlowSummary): "source" | "sink" | "sanitizer" | "transfer" {
    if (summary.ruleKind) {
        return summary.ruleKind;
    }
    if (summary.transfers.length > 0) return "transfer";
    if (summary.inputs.length === 0 && summary.outputs.length > 0) return "source";
    if (summary.inputs.length > 0 && summary.outputs.length === 0) return "sink";
    return "transfer";
}

function sinkTargetEndpoint(anchor: SemanticFlowAnchor, target: SemanticFlowSurfaceSlotRef): RuleEndpointOrRef | undefined {
    if (isRestArrayFormalSlot(anchor, target)) {
        return toRuleEndpoint(target);
    }
    return toRuleEndpoint(target);
}

function filterSemanticFlowSinkTargets(
    anchor: SemanticFlowAnchor,
    targets: SemanticFlowSurfaceSlotRef[],
): SemanticFlowSurfaceSlotRef[] {
    if (!isDatabaseOrStorageWriterAnchor(anchor) || isRawSqlExecutionAnchor(anchor)) {
        return targets;
    }
    const params = parseSignatureParameterTypes(anchor.methodSignature || "");
    return targets.filter(target => !isDatabaseControlOrSelectorSinkTarget(anchor, target, params));
}

function isDatabaseOrStorageWriterAnchor(anchor: SemanticFlowAnchor): boolean {
    const identity = [
        anchor.surface,
        anchor.owner,
        anchor.methodSignature,
        anchor.filePath,
    ].join(" ");
    if (!/\b(?:insert|update|upsert|save|persist|put|putsync|set|write)/i.test(identity)) {
        return false;
    }
    return /\b(?:rdb|relationalstore|database|db|sqlite|sql|dao|repository|store|storage|preferences|kv|bucket)\b/i.test(identity);
}

function isRawSqlExecutionAnchor(anchor: SemanticFlowAnchor): boolean {
    const identity = [
        anchor.surface,
        anchor.owner,
        anchor.methodSignature,
        anchor.filePath,
    ].join(" ");
    return /\b(?:executesql|execsql|querysql|rawquery|execdml|executes?|sql)\b/i.test(identity)
        && !/\b(?:insertdata|updatedata|insert|update|upsert)\b/i.test(String(anchor.surface || ""));
}

function isDatabaseControlOrSelectorSinkTarget(
    anchor: SemanticFlowAnchor,
    target: SemanticFlowSurfaceSlotRef,
    params: string[],
): boolean {
    if (target.slot !== "arg" || typeof target.index !== "number") {
        return false;
    }
    const index = target.index;
    const param = params[index]?.replace(/\s+/g, " ").trim().toLowerCase() || "";
    if (!param) {
        return false;
    }
    if (isDatabaseControlParameterType(param)) {
        return true;
    }
    if (index === 0 && isLikelyLeadingDatabaseSelector(anchor, params)) {
        return true;
    }
    return false;
}

function isDatabaseControlParameterType(param: string): boolean {
    return /\b(?:rdbpredicates|predicates?|predicate|where|filter|condition|criteria|selection|queryoption|callback|businesserror|error)\b/i.test(param)
        || /callback\s*</i.test(param)
        || /\bfunction\b|\(\s*.*=>/.test(param);
}

function isLikelyLeadingDatabaseSelector(anchor: SemanticFlowAnchor, params: string[]): boolean {
    if (params.length < 2) {
        return false;
    }
    const surface = String(anchor.surface || "");
    if (!/\b(?:insert|update|upsert|put|putsync|set)/i.test(surface)) {
        return false;
    }
    const first = params[0]?.replace(/\s+/g, "").toLowerCase() || "";
    if (!/^(string|uri|url|number)$/.test(first) && !/(table|key|uri|url|name|id)/i.test(first)) {
        return false;
    }
    return params.slice(1).some(param => !isDatabaseControlParameterType(param.toLowerCase()));
}

function isRestArrayFormalSlot(anchor: SemanticFlowAnchor, target: SemanticFlowSurfaceSlotRef): boolean {
    if (target.slot !== "arg") {
        return false;
    }
    const index = target.index ?? 0;
    const params = parseSignatureParameterTypes(anchor.methodSignature || "");
    if (index < 0 || index >= params.length) {
        return false;
    }
    const param = params[index].replace(/\s+/g, "");
    if (!/\[\]$/.test(param) && !/^Array<.+>$/.test(param)) {
        return false;
    }
    return params.length === 1 || index === params.length - 1;
}

function parseSignatureParameterTypes(signature: string): string[] {
    const start = signature.lastIndexOf("(");
    const end = signature.lastIndexOf(")");
    if (start < 0 || end <= start) {
        return [];
    }
    const body = signature.slice(start + 1, end).trim();
    if (!body) {
        return [];
    }
    const params: string[] = [];
    let depth = 0;
    let current = "";
    for (const ch of body) {
        if (ch === "<" || ch === "(" || ch === "[" || ch === "{") depth++;
        if (ch === ">" || ch === ")" || ch === "]" || ch === "}") depth = Math.max(0, depth - 1);
        if (ch === "," && depth === 0) {
            params.push(current.trim());
            current = "";
            continue;
        }
        current += ch;
    }
    if (current.trim()) {
        params.push(current.trim());
    }
    return params;
}

function buildModuleArtifact(anchor: SemanticFlowAnchor, summary: SemanticFlowSummary): SemanticFlowModuleArtifact {
    const moduleSpec = summary.moduleSpec
        ? canonicalizeAndValidate(materializeSemanticFlowModuleSpec(anchor, summary.moduleSpec))
        : inferModuleSpec(anchor, summary);
    return {
        kind: "module",
        moduleSpec,
    };
}

function materializeSemanticFlowModuleSpec(anchor: SemanticFlowAnchor, spec: ModuleSpec): ModuleSpec {
    const moduleId = sanitizeId(`semanticflow.${anchor.id}`);
    const ownerClassName = extractAnchorOwnerClassName(anchor);
    return {
        ...spec,
        id: !spec.id || spec.id === "semanticflow.inline" ? moduleId : spec.id,
        description: spec.description || `Generated by semantic flow pipeline for ${anchor.surface}.`,
        enabled: spec.enabled ?? true,
        semantics: spec.semantics.map(semantic => {
            if (semantic.kind !== "keyed_storage") {
                return semantic;
            }
            const storageClasses = semantic.storageClasses.map(item =>
                item === "__anchor_owner__" && ownerClassName ? ownerClassName : item,
            );
            return {
                ...semantic,
                storageClasses,
            };
        }),
    };
}

function inferModuleSpec(anchor: SemanticFlowAnchor, summary: SemanticFlowSummary): ModuleSpec {
    if (summary.moduleKind === "state" || summary.moduleKind === "declarative") {
        throw new Error(`moduleKind ${summary.moduleKind} requires explicit moduleSpec for ${anchor.id}`);
    }
    if (summary.transfers.length === 0) {
        throw new Error(`module summary requires at least one transfer or explicit moduleSpec: ${anchor.id}`);
    }
    const semantics = summary.transfers.map((transfer, index) => ({
        id: index === 0 ? undefined : `bridge-${index}`,
        kind: "bridge" as const,
        from: toModuleEndpoint(anchor, transfer.from),
        to: toModuleEndpoint(anchor, transfer.to),
        constraints: normalizeModuleConstraints(summary.relations?.constraints),
        dispatch: summary.relations?.trigger ? toModuleDispatch(anchor, summary, transfer) : undefined,
    }));
    return canonicalizeAndValidate({
        id: sanitizeId(`semanticflow.${anchor.id}`),
        description: `Generated by semantic flow pipeline for ${anchor.surface}.`,
        enabled: true,
        semantics,
    });
}

function normalizeModuleConstraints(constraints?: ModuleConstraint[]): ModuleConstraint[] | undefined {
    if (!constraints || constraints.length === 0) {
        return undefined;
    }
    const hasSameAddress = constraints.some(constraint => constraint.kind === "same_address");
    const normalized = hasSameAddress
        ? constraints.filter(constraint => constraint.kind !== "same_receiver")
        : constraints;
    return normalized.length > 0 ? normalized : undefined;
}

function canonicalizeAndValidate(spec: ModuleSpec): ModuleSpec {
    validateModuleSpecOrThrow(spec);
    return canonicalizeModuleSpec(spec);
}

function toModuleDispatch(
    anchor: SemanticFlowAnchor,
    summary: SemanticFlowSummary,
    transfer?: SemanticFlowSummary["transfers"][number],
): ModuleDispatch {
    const trigger = summary.relations?.trigger;
    if (!trigger) {
        throw new Error(`missing trigger for ${anchor.id}`);
    }
    const via = transfer?.to.slot === "callback_param"
        ? undefined
        : trigger.via ? toModuleEndpoint(anchor, trigger.via) : undefined;
    return {
        preset: trigger.preset,
        via,
        reason: trigger.reason,
    };
}

function toModuleEndpoint(anchor: SemanticFlowAnchor, ref: SemanticFlowSurfaceSlotRef): ModuleEndpoint {
    const invokeBase = {
        surface: ref.surface || anchor.surface,
        ...(ref.fieldPath ? { fieldPath: ref.fieldPath } : {}),
    };
    const methodBase = {
        surface: toMethodSurface(anchor, ref.surface),
        ...(moduleFieldLoadTail(ref).length > 0 ? { fieldPath: moduleFieldLoadTail(ref) } : {}),
    };
    switch (ref.slot) {
        case "arg":
            if (typeof ref.index !== "number") throw new Error(`arg slot requires index for ${anchor.id}`);
            return { ...invokeBase, slot: "arg", index: ref.index };
        case "base":
            return { ...invokeBase, slot: "base" };
        case "result":
            return { ...invokeBase, slot: "result" };
        case "callback_param":
            return {
                ...invokeBase,
                slot: "callback_param",
                callbackArgIndex: ref.callbackArgIndex,
                paramIndex: ref.paramIndex,
            };
        case "method_this":
            return { ...methodBase, slot: "method_this" };
        case "method_param":
            if (typeof ref.paramIndex !== "number") throw new Error(`method_param slot requires paramIndex for ${anchor.id}`);
            return { ...methodBase, slot: "method_param", paramIndex: ref.paramIndex };
        case "field_load":
            if (!ref.fieldName) throw new Error(`field_load slot requires fieldName for ${anchor.id}`);
            return { ...methodBase, slot: "field_load", fieldName: ref.fieldName };
        case "decorated_field_value":
            return { ...invokeBase, slot: "decorated_field_value" };
        default:
            throw new Error(`unsupported module endpoint slot ${(ref as any).slot}`);
    }
}

function toMethodSurface(anchor: SemanticFlowAnchor, surface: SemanticFlowSurfaceSlotRef["surface"] | undefined) {
    if (surface && typeof surface === "object" && (surface as any).kind === "method") {
        return surface;
    }
    const selector: Record<string, unknown> = {};
    if (anchor.methodSignature) {
        selector.methodSignature = anchor.methodSignature;
    }
    if (anchor.surface) {
        selector.methodName = anchor.surface;
    }
    if (anchor.owner) {
        selector.declaringClassName = anchor.owner;
    }
    return {
        kind: "method" as const,
        selector,
    };
}

function moduleFieldLoadTail(ref: SemanticFlowSurfaceSlotRef): string[] {
    const path = Array.isArray(ref.fieldPath) ? ref.fieldPath.map(part => String(part)).filter(Boolean) : [];
    if (ref.slot !== "field_load" || !ref.fieldName || path[0] !== ref.fieldName) {
        return path;
    }
    return path.slice(1);
}

function toRuleEndpoint(ref: SemanticFlowSurfaceSlotRef): RuleEndpointOrRef {
    const path = normalizeFieldPath(ref.fieldPath);
    if (ref.slot === "arg") {
        if (typeof ref.index !== "number") throw new Error("arg slot requires index");
        return path ? { endpoint: `arg${ref.index}` as RuleEndpoint, path } : (`arg${ref.index}` as RuleEndpoint);
    }
    if (ref.slot === "result") return path ? { endpoint: "result", path } : "result";
    if (ref.slot === "base") return path ? { endpoint: "base", path } : "base";
    if (ref.slot === "field_load") {
        return {
            endpoint: "base",
            path: [ref.fieldName || ""].filter(Boolean),
        };
    }
    throw new Error(`slot ${ref.slot} is not representable as a rule endpoint`);
}

function normalizeFieldPath(fieldPath?: any): string[] | undefined {
    if (!fieldPath) return undefined;
    return Array.isArray(fieldPath) ? fieldPath.map(part => String(part)) : undefined;
}

function requireAnchorSignature(anchor: SemanticFlowAnchor): string {
    const signature = anchor.methodSignature || anchor.method?.getSignature?.()?.toString?.();
    if (!signature) {
        throw new Error(`anchor.methodSignature missing: ${anchor.id}`);
    }
    return signature;
}

function extractAnchorOwnerClassName(anchor: SemanticFlowAnchor): string | undefined {
    const owner = String(anchor.owner || "").trim();
    if (!owner) {
        return undefined;
    }
    const colonIndex = owner.lastIndexOf(":");
    const raw = colonIndex >= 0 ? owner.slice(colonIndex + 1) : owner;
    const normalized = raw.trim();
    return normalized || undefined;
}

export function consolidateSemanticFlowAnalysisAugmentByFootprint(
    augment: SemanticFlowAnalysisAugment,
): SemanticFlowAnalysisAugment {
    return {
        ...augment,
        ruleSet: consolidateRuleSetByFootprint(augment.ruleSet),
        moduleSpecs: consolidateModuleSpecsByFootprint(augment.moduleSpecs),
        arkMainSpecs: consolidateArkMainSpecsByFootprint(augment.arkMainSpecs),
    };
}

export function consolidateArkMainSpecsByFootprint(specs: ArkMainSpec[]): ArkMainSpec[] {
    const out = new Map<string, ArkMainSpec>();
    for (const spec of specs) {
        const key = JSON.stringify({
            selector: spec.selector,
            entryPattern: spec.entryPattern,
        });
        if (!out.has(key)) {
            out.set(key, spec);
        }
    }
    return [...out.values()];
}

function consolidateModuleSpecsByFootprint(specs: ModuleSpec[]): ModuleSpec[] {
    const out = new Map<string, ModuleSpec>();
    for (const spec of specs) {
        const canonical = canonicalizeAndValidate(spec);
        const key = JSON.stringify({
            semantics: canonical.semantics.map(semantic => stripSemanticIds(semantic)),
        });
        if (!out.has(key)) {
            out.set(key, canonical);
        }
    }
    return [...out.values()];
}

function consolidateRuleSetByFootprint(ruleSet: TaintRuleSet): TaintRuleSet {
    return {
        ...ruleSet,
        sources: consolidateRulesByFootprint(ruleSet.sources || [], rule => ({
            kind: "source",
            match: rule.match,
            scope: rule.scope,
            calleeScope: rule.calleeScope,
            sourceKind: rule.sourceKind,
            target: rule.target,
            callbackArgIndexes: rule.callbackArgIndexes,
        })),
        sinks: consolidateRulesByFootprint(ruleSet.sinks || [], rule => ({
            kind: "sink",
            match: rule.match,
            scope: rule.scope,
            target: rule.target,
        })),
        sanitizers: consolidateRulesByFootprint(ruleSet.sanitizers || [], rule => ({
            kind: "sanitizer",
            match: rule.match,
            scope: rule.scope,
            target: rule.target,
        })),
        transfers: consolidateRulesByFootprint(ruleSet.transfers || [], rule => ({
            kind: "transfer",
            match: rule.match,
            scope: rule.scope,
            from: rule.from,
            to: rule.to,
        })),
    };
}

function consolidateRulesByFootprint<T>(rules: T[], footprint: (rule: T) => unknown): T[] {
    const out = new Map<string, T>();
    for (const rule of rules) {
        const key = JSON.stringify(footprint(rule));
        if (!out.has(key)) {
            out.set(key, rule);
        }
    }
    return [...out.values()];
}

function stripSemanticIds<T extends { id?: string }>(semantic: T): Omit<T, "id"> {
    const { id: _ignored, ...rest } = semantic;
    return rest;
}

function sanitizeId(value: string): string {
    const normalized = value
        .toLowerCase()
        .replace(/[^a-z0-9.-]+/g, "-")
        .replace(/-+/g, "-")
        .replace(/\.+/g, ".")
        .replace(/^[-.]+|[-.]+$/g, "");
    return normalized || "semanticflow";
}

function sourceRuleId(idBase: string, index: number): string {
    return index === 0 ? `${idBase}.source` : `${idBase}.source.${index}`;
}

function sinkRuleId(idBase: string, index: number): string {
    return index === 0 ? `${idBase}.sink` : `${idBase}.sink.${index}`;
}

function sanitizerRuleId(idBase: string, index: number): string {
    return index === 0 ? `${idBase}.sanitizer` : `${idBase}.sanitizer.${index}`;
}

function transferRuleId(idBase: string, index: number): string {
    return index === 0 ? `${idBase}.transfer` : `${idBase}.transfer.${index}`;
}

